### ISSUE TITLE
UyVR ?

### ISSUE THREAD

**Issue by Entretoize** [praydog/UEVR#103]
Many games are not UE games, I don't have the statistics, but I suppose many are Unity games and more VR games would be great.

After looking at some of your sources (quickly), it seems that hooks are more about DirectX than about UE, then some adjustments could make it work with Unity games too.

Maybe I'm totally wrong because I miss some time to better check the source, but you'll tell if that's possible...

**Comment by praydog** [comment]
No. This is an engine level mod.

**Comment by drhouse** [comment]
As a closed topic, I don't know if this will be seen, but does this mean that none of the methods used around UEVR could be applicable towards any kind of Unity VR injector? might VorpX's method be possible to integrate?

**Comment by Entretoize** [comment]
I think all directx methods can be used for unity games, but they don't
seem to be interested in doing that.
Vorpx method is horrible...


Cordialement, Grégory Defaisse

**Comment by praydog** [comment]
You are making wild assumptions. You CANNOT just use DirectX to achieve what is being done here. Further investigation of the code would reveal that there are tons of hooks aimed at Unreal Engine to achieve pretty much anything here. DirectX is only used to copy textures, perform some composition in this mod, not 6dof, not motion controls, not stereoscopic 3D.
