### ISSUE TITLE
failed to inject plugin nullifier

### ISSUE THREAD

**Issue by zerodzetag** [praydog/UEVR#11]
![2024-01-01_16h54_00](https://github.com/praydog/UEVR/assets/155151625/e42db39b-272d-4cb4-b65c-8a36ceffca80)

people in dc said it is because of windows defender or anti virus
i uninstall my antivirus and turn off still doesn't help 
tried 2 games on the list robocop and aliens

**Comment by praydog** [comment]
Reinstall the mod with the folder whitelisted in your anti-virus. It likely deleted the plugin nullifier prior to injection.

**Comment by zerodzetag** [comment]
> Reinstall the mod with the folder whitelisted in your anti-virus. It likely deleted the plugin nullifier prior to injection.

i uninstall my antivirus already. and still didn't get it work

**Comment by praydog** [comment]
> > Reinstall the mod with the folder whitelisted in your anti-virus. It likely deleted the plugin nullifier prior to injection.
> 
> i uninstall my antivirus already. and still didn't get it work

Download the mod again.

**Comment by zerodzetag** [comment]
> > > Reinstall the mod with the folder whitelisted in your anti-virus. It likely deleted the plugin nullifier prior to injection.
> > 
> > 
> > i uninstall my antivirus already. and still didn't get it work
> 
> Download the mod again.

re download thousands of time. no anti virus. defender off. still the same

**Comment by praydog** [comment]
User commented that they moved UEVR from their OneDrive folder to their D:/ drive root and it worked fine.

**Comment by JibJab1980** [comment]
I'm getting the same error, tried reinstalling game and moved mod to c: root drive.  Will donate as soon as I can get the mod working any help would be hugely appreciated. I also seem to be stuck in theatre mode for your previous mods ?

**Comment by praydog** [comment]
After some testing, found out this is because there are special characters in the path that UEVR is in. You need to move it somewhere else for the time being.

**Comment by praydog** [comment]
Current build has been replaced with one that fixes this path issue: https://github.com/praydog/UEVR/releases/download/1.0/UEVR.zip

However this does not account for issues that may crop up where the game does not have permission to access the drive or folder that UEVR resides in.

**Comment by praydog** [comment]
Release 1.01 should fix this issue as well as the shortcut issue: https://github.com/praydog/UEVR/releases/tag/1.01
