### ISSUE TITLE
[FEATURE REQUEST] More save options of already present transformation options.

### ISSUE THREAD

**Issue by Pande4360** [praydog/UEVR#111]
Back to RoN: I found there are several issues with even with 6dof working. These issues are probably not the fault of UEVR but UEVR could solve them.
1. Scale of items is generally wrong.
2. Rotation of certain objects seem to be slightly diffrent from flat. 

SOLUTION:
I found that UEVR could temporarily fix those issues easily with the already present options, e.g. relative location/rotatioin, and scale settings. 
I just cant save them currently.

**Comment by praydog** [comment]
They can be saved in the current dev builds. You can find these under Actions. On this repository.
