### ISSUE TITLE
Configurable In-Game Menu key

### ISSUE THREAD

**Issue by rodrigoqueiroz** [praydog/UEVR#112]
**Is your feature request related to a problem? Please describe.**
Some keyboards do not have an insert key and you can not open the in-game menu once closed. 
The L3+R3 shortcut helps, but sometimes you are not using controllers. Additionally, If you are using Virtual Desktop the L3+R3 shortcut is already used by the metrics overlay.

**Describe the solution you'd like**
An config option to assign another keyboard key (example, End) to open the in-game menu.

**Comment by praydog** [comment]
This is already modifiable under "FrameworkConfig".
