### ISSUE TITLE
Could not Create OpenXR openxr instance  -10

### ISSUE THREAD

**Issue by VRMatters** [praydog/UEVR#113]
**Describe the bug*
![ui](https://github.com/praydog/UEVR/assets/156135223/e67b3ced-ec0a-4172-8047-c84b336b8774)
*

t was still working normally yesterday. As of today, no game switches to VR anymore. Instead, I get this error message..

Could not Create OpenXR openxr instance  -10

**Comment by praydog** [comment]
Delete or rename the existing OpenXR plugin that is in your game's plugins folder.

**Comment by VRMatters** [comment]
_Thank you Sooooo much *g*

**Comment by seasaltaa** [comment]
sir  PLZ
![3336](https://github.com/praydog/UEVR/assets/156638908/34676e82-5baa-4745-ac17-cae3439d4e18)
Could not Create OpenXR openxr instance : -2
openvr_api.dll not found

**Comment by seasaltaa** [comment]
and it does not work with other games (it works before)

**Comment by praydog** [comment]
-2 is XR_ERROR_RUNTIME_FAILURE, different from the original post here. This is outside of UEVR's control and you may need to look up this error (XR_ERROR_RUNTIME_FAILURE) and your headset model and check if others have found a solution.

**Comment by seasaltaa** [comment]
how  could i get uevr and its settings back to their original state   sir

**Comment by seasaltaa** [comment]
since i import config of ready or not from others and "delete the openxr from game's plugins" it happend and did not work with any games()
