### ISSUE TITLE
[Request] Provide alternative ways to enable Dpad for controllers without thumb rest"

### ISSUE THREAD

**Issue by Kassender** [praydog/UEVR#114]
For Pico 4 controller for example, without DPAD native on the controller, an alternative to generate Dpad actions would be very appreciated.

**Comment by MichaelTkach94** [comment]
+

**Comment by Zod1234** [comment]
curious, how you want it implemented.

**Comment by praydog** [comment]
Looking into a gesture based solution (hand near head or near waist to initiate shifting)

**Comment by FolkSong** [comment]
Nice title ; ) But now the other one was updated so we have duplicates.

Anyway great to hear it's being worked on, thanks praydog!

#14

**Comment by praydog** [comment]
Duplicate issue #14, will continue convo there
