### ISSUE TITLE
[BUG]OpenXRtool Kit causes many crash in several games

### ISSUE THREAD

**Issue by ImmersiveGamesTV** [praydog/UEVR#119]
**Describe the bug**

A clear and concise description of what the bug is. If the bug only started to happen after a certain UEVR update, let us know which version the bug appeared in.

**Upload logs and any crash dumps**

If this is a game crash or game bug:

UEVR-specific logs and crash dumps:

* Click "Open Global Dir" in the injector frontend
* Navigate to the offending game folder
* Zip up the folder
* Upload to the issue

Game-specific crash dumps:

* These can usually be found in `%LOCALAPPDATA%/{the_game_name}/Saved/Crashes`
* Once found, zip up the folder and upload

**Identify the UEVR version**

If the UEVR version or commit hash is known, submit this information.

**To Reproduce**

**Expected behavior**

**Screenshots**

**PC Specs (please complete the following information):**
 - OS (e.g. Windows 11)
 - Graphics card
 - CPU
 - Headset Model
 - OpenXR or OpenVR
 - Streamer if applicable (Link, Air Link, Virtual Desktop, Steam Link, ALVR, etc...)
 - If using OpenXR, the runtime (Oculus, SteamVR, VDXR, PimaxXR, etc...)

**Comment by ImmersiveGamesTV** [comment]
after VR injection, in openxr mode, in combination with openxr tool kit (witch allows many FPS improvements), in somes games it works, with others it works and crash after a few minutes and others after seconds. the crash log mention openxrtool kit

Meta Quest 3 (Quest link (oculus runtime, and virtual desktop, vdxr)

I9 9900KS
RTX 3090 Founders edition

**Comment by praydog** [comment]
Duplicate issue #44

And this may not be an issue with UEVR as the crash seen is directly within OXRTK's code.
