### ISSUE TITLE
[BUG] The Talos Principle 2 Crash report UE

### ISSUE THREAD

**Issue by artemcdk** [praydog/UEVR#123]
Сrashes after about 10-15 seconds, also during loading, tried all kinds of combinations of graphics settings and helmet resolution, switched the “Enable depth” checkbox in Ureal frameworks.
[Crashes.zip](https://github.com/praydog/UEVR/files/13926887/Crashes.zip)
[Talos2-Win64-Shipping.zip](https://github.com/praydog/UEVR/files/13926888/Talos2-Win64-Shipping.zip)

**Comment by praydog** [comment]
Disable OpenXR toolkit

**Comment by praydog** [comment]
#44

**Comment by artemcdk** [comment]
this helped, thank you very much!
