### ISSUE TITLE
[Unreal 5.2.1] TRYP FPV crashing after seconds/minutes

### ISSUE THREAD

**Issue by Myrothas** [praydog/UEVR#13]
In TRYP FPV i keep getting crashes.
100% crash when it hits a loading screen.
Randomly crashes.

System:

5800X3D, 4080, 32GB Ram, Win10, Virtual Desktop on VDXR

Settings: 

OpenXR, UEVR VR_RenderingMethod: Synced Sequential & Ghosting fix on

Fatal error!

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x000000020000b010

0x00007ffe0afd39f9 XR_APILAYER_MBUCCHIA_toolkit.dll!UnknownFunction []
0x00007ffe0afdd064 XR_APILAYER_MBUCCHIA_toolkit.dll!UnknownFunction []
0x00007ffe0afddd4e XR_APILAYER_MBUCCHIA_toolkit.dll!UnknownFunction []
0x00007ff7c86d5237 TrypFPV-Win64-Shipping.exe!FD3D12DescriptorCache::SetRenderTargets() [F:\Github\Unreal\Engine\Source\Runtime\D3D12RHI\Private\D3D12DescriptorCache.cpp:270]
0x00007ff7c870c1c0 TrypFPV-Win64-Shipping.exe!FD3D12StateCache::ApplyState() [F:\Github\Unreal\Engine\Source\Runtime\D3D12RHI\Private\D3D12StateCache.cpp:522]
0x00007ff7c86ce35e TrypFPV-Win64-Shipping.exe!FD3D12CommandContext::RHIDrawPrimitive() [F:\Github\Unreal\Engine\Source\Runtime\D3D12RHI\Private\D3D12Commands.cpp:1559]
0x00007ff7c941083a TrypFPV-Win64-Shipping.exe!FRHICommandListBase::Execute() [F:\Github\Unreal\Engine\Source\Runtime\RHI\Private\RHICommandList.cpp:587]
0x00007ff7c940bf78 TrypFPV-Win64-Shipping.exe!<lambda_e5ade85d47f4eccb3a37d208133dfbea>::operator()() [F:\Github\Unreal\Engine\Source\Runtime\RHI\Private\RHICommandList.cpp:799]
0x00007ff7c941083a TrypFPV-Win64-Shipping.exe!FRHICommandListBase::Execute() [F:\Github\Unreal\Engine\Source\Runtime\RHI\Private\RHICommandList.cpp:587]
0x00007ff7c940bcef TrypFPV-Win64-Shipping.exe!<lambda_c3c45769530a4e2f62785b74e714d2da>::operator()() [F:\Github\Unreal\Engine\Source\Runtime\RHI\Private\RHICommandList.cpp:899]
0x00007ff7c6757f8d TrypFPV-Win64-Shipping.exe!TGraphTask<TFunctionGraphTaskImpl<void __cdecl(void),0> >::ExecuteTask() [F:\Github\Unreal\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:1311]
0x00007ff7c800a5ae TrypFPV-Win64-Shipping.exe!FNamedTaskThread::ProcessTasksUntilQuit() [F:\Github\Unreal\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:648]
0x00007ff7c9476eeb TrypFPV-Win64-Shipping.exe!FRHIThread::Run() [F:\Github\Unreal\Engine\Source\Runtime\RenderCore\Private\RenderingThread.cpp:334]
0x00007ff7c81699e7 TrypFPV-Win64-Shipping.exe!FRunnableThreadWin::Run() [F:\Github\Unreal\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:149]
0x00007ff7c8164241 TrypFPV-Win64-Shipping.exe!FRunnableThreadWin::GuardedRun() [F:\Github\Unreal\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:79]
0x00007ffedc367344 KERNEL32.DLL!UnknownFunction []
0x00007ffedc6a26b1 ntdll.dll!UnknownFunction []

Crash in runnable thread RHIThread

**Comment by praydog** [comment]
Disable OpenXR toolkit.

**Comment by Myrothas** [comment]
This fixed it, thank you! <3
