### ISSUE TITLE
[BUG] Headset Lens Rendering Issue

### ISSUE THREAD

**Issue by soundtrapuser448** [praydog/UEVR#132]
**Describe the bug**

Every time I inject the mod in either ABZU or Ancestors: Humankind Odyssey, The left lens of my headset renders the game differently compared to the right. This makes the experiences unplayable as it causes eye strain. I tried reinstalling UEVR, restarting my computer and restarting Steam multiple times. I've tried using the 1.03 and 1.02 version, but nothing seems to fix the issue. :( 

I'm wondering if it might have to do with some settings in Steam? I followed every step in the video tutorial for UEVR installation so I'm not sure what's causing this

**PC Specs (please complete the following information):**
 - OS: Windows
 - RTX 4070Ti
 - 5800X3D
 - Quest 2
 - OpenXR and OpenVR
 - OpenXR: Oculus

**Comment by praydog** [comment]
Use Synchronized Sequential rendering method within the UEVR settings. Go to the Flat2VR discord where users have figured out individual settings for each game.
