### ISSUE TITLE
Could not Create OpenXR openxr instance : -2

### ISSUE THREAD

**Issue by seasaltaa** [praydog/UEVR#133]
sir PLZ
![3336](https://github.com/praydog/UEVR/assets/156638908/d97cc666-64d9-435d-bc7a-76c427859526)

Could not Create OpenXR openxr instance : -2
openvr_api.dll not found

and it works before

**Comment by seasaltaa** [comment]
i've delete the existing OpenXR plugin that is in game's plugins folder.

**Comment by praydog** [comment]
This is an issue with your OpenXR runtime, not UEVR. This is `XR_ERROR_RUNTIME_FAILURE` which is not on our end. Not related at all to deleting OpenXR plugins.

**Comment by Kriosym** [comment]
> sir PLZ ![3336](https://private-user-images.githubusercontent.com/156638908/296660331-d97cc666-64d9-435d-bc7a-76c427859526.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg3NzA5NDcsIm5iZiI6MTcwODc3MDY0NywicGF0aCI6Ii8xNTY2Mzg5MDgvMjk2NjYwMzMxLWQ5N2NjNjY2LTY0ZDktNDM1ZC1iYzdhLTc2YzQyNzg1OTUyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyNFQxMDMwNDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYWZlMjNhMWNkYWVkMjRjODY2NjIzMzU0ZDhhZWZhZDQwYmE0Mzk2ZTkwOGYxMjQ3YzYyMTQ3ZTQzM2IyNzllJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.g2dwy1LSG_h4Qo9H3ciZAKvfBRF4oyNZNVVott17LoU)
> 
> Could not Create OpenXR openxr instance : -2 openvr_api.dll not found
> 
> and it works before

I was having a similar issue, was caused by a reshade instance of OpenXR in the programdata folder that had to be deleted. Not sure if it will be applicable for you but it's easy to try and worth a shot, see fix here -> https://github.com/praydog/UEVR/issues/147

**Comment by chaminar2** [comment]
> This is an issue with your OpenXR runtime, not UEVR. This is `XR_ERROR_RUNTIME_FAILURE` which is not on our end. Not related at all to deleting OpenXR plugins.

so how do you fix "an issue with you openXR rutime" .......... ?
