### ISSUE TITLE
per gaming setting to adjust gun alignnent

### ISSUE THREAD

**Issue by Zod1234** [praydog/UEVR#136]
a few configs I've used from the discord have the guns tilted back too much and have to uncomfortably tilt the wrists forward for proper aiming.  I'm on a quest2 and I suspect some of the configs were made with a different hmd/controller set.  an example of this is six days in fallujah.  I tried in steamvr and openxr and airlink and all exhibited this issue.

if it's not possible to make an offset slider it seems configs per device/controller type would be needed for each game.  maybe good practice would be for people who post configs to state what device it was made on.

**Comment by praydog** [comment]
Fixed in 167a1afd0011fa4dd6afd56372664d11cc1eee5f

Developer builds can be downloaded from [the Actions page](https://github.com/praydog/UEVR/actions)
or you can wait for the next build to be released
