### ISSUE TITLE
[BUG] UEVR sees Adobe products as Unreal games

### ISSUE THREAD

**Issue by Olfdev** [praydog/UEVR#143]
**Describe the bug**

UEVR sees Adobe products as Unreal games and creates a profile for them. 

**Identify the UEVR version**

UEVR Beta 1.03

**To Reproduce**

1. Start any Adobe product 
2. Start UEVR 
3. Observe that the Adobe product appears in the list

**Expected behavior**

Adobe products should not appear in the list. 

**Screenshots**
![Screenshot_20240118-123055](https://github.com/praydog/UEVR/assets/80658604/f98de958-40ce-4a23-a873-ca13fac85f4a)

**Comment by praydog** [comment]
Fixed in https://github.com/praydog/uevr-frontend/commit/0e16583be44c428477b65ce9f9899ab86bba35e3

**Comment by Olfdev** [comment]
Sorry to reopen this but notepad.exe is also seen as an Unreal game.

**Comment by praydog** [comment]
Added

**Comment by Ronln** [comment]
Can you fix notepad++.exe  also please.
