### ISSUE TITLE
Onward VR Problem

### ISSUE THREAD

**Issue by mattwiz318** [praydog/UEVR#145]
[BUG] When opening the game ONWARD, which is natively vr, I get a loading message saying "Oculus VR Plugin (Unknown Engine)" and this makes my controllers point to complete opposite direction and makes head movement very shaky and laggy. Is there anything I can do?

**Comment by mattwiz318** [comment]
For anyone with the same issue, I Uninstalled and removed UEVR and Onward from my computer and also set the xr runtime in the oculus settings to default and this worked for me. However i'm not sure if this is a legitimate solution or if it just worked by chance to so keep that in mind.

**Comment by praydog** [comment]
Onward is a Unity game, not an Unreal game. It's also a native VR game... not sure why this issue was made here.
