### ISSUE TITLE
OpenXR not loaded: Could not create openxr instance: -32

### ISSUE THREAD

**Issue by TravsVoid** [praydog/UEVR#147]
I had no issue using Air Link with OpenXR when UEVR first came out but then I got the bright idea to try out SteamVR to compare and ever since I can't get UEVR to work through Air Link with OpenXR. Of course I can still get OpenVR to work while using Steam Link but I would like to know how to go back. The Oculus app says it's the active OpenXR Runtime and I even tried some OpenXR-Runtime-Switcher app someone made and that also made no difference.

My problems started with SteamVR so I even tried uninstalling it and that made no difference. I checked my System Variables like another thread suggested and XR_RUNTIME_JSON was not listed. I also tried uninstalling games and reinstalling them which also made no difference. I haven't tried reinstalling the Oculus app yet but I'm really tempted to just reinstall Windows next.

**Comment by praydog** [comment]
-32 is `XR_ERROR_FILE_ACCESS_ERROR`.

I suggest you look elsewhere in regards to this error as I am not trying to provide general OpenXR support here. 

This is a resource from OpenXR Toolkit's documentation talking about it: https://mbucchia.github.io/OpenXR-Toolkit/troubleshooting.html#missing-visual-c-system-component

**Comment by mbucchia-msft** [comment]
ReShade shouldn't install their API layer to `%ProgramData%`. I've reported the issue on their Discord: https://discord.com/channels/586242553746030596/609352379351171076/1199069198849167481

**Comment by Kriosym** [comment]
> I figured it out, ReShade was the culprit. Someone in a forum mentioned to check the registry at: `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Khronos\OpenXR\1\ApiLayers\Implicit` I saw ReShade there which linked to this folder: `C:\ProgramData\ReShade` After deleting that folder my issue was gone!
> 
> One other note, the error that showed up in OpenXR Tools was different then the one you specified, it said XR_ERROR_RUNTIME_FAILURE.

Thank you @TravsVoid that was exactly my issue, also fixed other problems I had been having with OpenXR!
