### ISSUE TITLE
Flickering screen when injector is running [BUG]

### ISSUE THREAD

**Issue by Asryan2a** [praydog/UEVR#149]
Hi

i've tried to play Robocop with UEVR injector

1. I use Virtual desktop
2. I launched UEVR in admin
3. i launched the game 
4. alt tap to inject

All is flickering and unplayable, what can i do to fix this?  
https://www.youtube.com/watch?si=NbFrO2WQUBd06Z8e&fbclid=IwAR0xq7Sylneh8qgJtwv6mPXvPX9LHw730IgBASt78E2POG5IHO5rNNvAVuE&v=MQ0Pjr19c4Y&feature=youtu.be

is seems that weirdly steam vr is launching when i run the game is it normal?

I run a 4090 on a i7 14700k

**Comment by praydog** [comment]
Disable DLSS frame generation. It is not supported in VR.

You can also disable hardware accelerated GPU scheduling in your Windows graphics settings.
