### ISSUE TITLE
AHUD Screen Space Rendering

### ISSUE THREAD

**Issue by Xeth84** [praydog/UEVR#162]
Please render AHUD elements at the same plane as the UI

AHUD elements are not yet handled by UEVR as they are rendered separately from Slate UI/UMG stuff. Sometimes referred to as screen space rendering.

When the AHUD elements are rendered they are blurry and really far apart for each eye since they are right in front of the player's face.  I see this most for dialogue sequences, but most recently, the elements are the objectives, so I have no idea where to go.  For the dialogues, I have to turn on 2D mode to see anything. The 4 games that have seen this are Bloodstained, Asterigos, Sinking City, and Styx?  So that means this plagues a lot more games as I have not tried many games yet.

**Comment by praydog** [comment]
Pretty much fixed over the course of several commits. Last few ones have included support for Scaleform as well. Games like Bloodstained are outliers that will require a different fix. Requires "AHUD UI compatibility fix" to be enabled. Also has debug options under "debug" when this option is enabled to go through a selection of possible render targets if UEVR cannot automatically fix it.
