### ISSUE TITLE
Camera manipulation (rotational)

### ISSUE THREAD

**Issue by randomVRguy** [praydog/UEVR#167]
I tested Ride 4 (motorcycle game) in first person and found that I would need a further adjustment for camera rotation. Here's the problem: the VR viewport is rigidly tied to the motorcycle model (that's just how it's coded in the game). Now, when I turn (so left/right controller input), the viewport moves exactly left/right too which is very annoying in VR (an inexperienced person would immediately get motion sickness). I tested then "freeze rotation" and that feels way more natural and comes actually close to real life (I'm a motorcyclist). BUT the problem is, COMPLETE rotation of the yaw axis is now freezed (of course), so after a longer corner I'm sitting on the motorcycle looking backwards :D 
So here's the point: I would need an option to let's say gradually adjust the "freeze rotation" option. What I mean by that is, it has to **absorb short, quick** rotational movements but a **slower rotation of the viewport must be is allowed** (correction while driving long smooth corners). I know it's technically possible, bc some car racing games with good VR support provide such an option for the pitch axis (which avoids horizon shaking _without_ full horizon lock). That would help so much for every bike game running in UEVR! Thanks in advance!

**Comment by praydog** [comment]
First thing that comes to mind here is to just add an interpolation option for the original camera rotation.

**Comment by randomVRguy** [comment]
Ok, but how should that work in detail?

**Comment by praydog** [comment]
I think either lerping or combining it with something akin to a rotational "deadzone" would work.

**Comment by randomVRguy** [comment]
Sounds like a good attempt. Would like to try it.

**Comment by randomVRguy** [comment]
Any hope that something like this gets implemented in the next build?

**Comment by praydog** [comment]
Added.

**Comment by randomVRguy** [comment]
I tested it and it worked out great, it really solves the problem... _except that it comes with a new problem_: During "driving a long corner", so due to a longer input from the camera thumbstick, the viewport does a quick 360° rotation in the respective axis. Seems to be a consequence of the math behind the lerp thing... Would be cool if that can be solved. Other than that, perfect feature!

**Comment by InHard2** [comment]
Hey i cant seem to make Any RE games with the vr mod work, in the screen it looks fine and the rotation doesnt lag or frezze, but in my vr headset it frezzes when i look too muhc to teh right ot left
