### ISSUE TITLE
When i press Inject nothing happen.

### ISSUE THREAD

**Issue by therealnova** [praydog/UEVR#17]
Hi, I'm having trouble with the injector. I've unpacked it in a folder under Windows 10 and then started the injector with admin rights. After that, I launched Robocop and, of course, set OpenXR as the default in the Oculus app. Then I connected my Meta Quest 3 to my computer with a Link cable. After loading the level in Robocop, I switched the injector to OpenXR, selected Robocop from the dropdown menu and pressed 'Inject'. The button lights up briefly, but nothing happens. I tried the same with two other games (Satisfactory), but again nothing happened. I restarted the computer and redownloaded the program, but it still doesn't work. What am I doing wrong? My PC specs are: Nvidea 3090, Win 10, Quest 3, link cable.

Under \Roaming\UnrealVRMod there was only the three folder from the games. In each folder, there was only the config.txt file. There was nothing more in the folders.

[config.txt](https://github.com/praydog/UEVR/files/13806455/config.txt)

**Comment by praydog** [comment]
Redownload UEVR.zip and try again, I've replaced the executable with a fix as described here: https://github.com/praydog/UEVR/issues/11#issuecomment-1873536773

**Comment by drewkcutler** [comment]
I'm having the same issue with both satisfactory and borderlands 3, but am using a quest 2 with wireless quest link, is there in issue with this setup?

**Comment by praydog** [comment]
Release 1.01 should fix this. https://github.com/praydog/UEVR/releases/tag/1.01

**Comment by drewkcutler** [comment]
> Release 1.01 should fix this. https://github.com/praydog/UEVR/releases/tag/1.01

I reinstalled with that release but it didn't work, but tried like 15 times and it just worked it eventually, thanks

**Comment by transdodo** [comment]
> > Release 1.01 should fix this. https://github.com/praydog/UEVR/releases/tag/1.01
> 
> I reinstalled with that release but it didn't work, but tried like 15 times and it just worked it eventually, thanks

I'm sorry im currently having same issue ..even after the New version. When I click inject button it glow for a second and then nothing happens. What do you mean by 15 times like clicking one after another untill it works

**Comment by JonkHunkle** [comment]
i was having this issue as well while trying to run sea of thieves / deep rock galactic

took a second to realize both games are earlier versions of unreal (0.125 and 4.27 respectively) and that could be what's causing my issue.

currently redownloading the outer worlds (v) to see if my suspicions are correct

**Comment by transdodo** [comment]
> i was having this issue as well while trying to inject sea of thieves / deep rock galactic with a meta quest 3
> 
> took a second to realize both games are earlier versions of unreal (0.125 and 4.27 respectively) and that could be what's causing my issue.
> 
> currently redownloading the outer worlds to see if my suspicions are correct

No that not my case I tried efootball 23 and forgive me father 2 .and that only because I've seen some playing these game smoothly. I'm not sure what should I do ? Any suggestions

**Comment by therealnova** [comment]
Thank you, Praydog, for your support. But, unfortunately, I have to say it's not working. Absolutely nothing has changed. I've now also placed euvr directly under C:\uevr\ and turned off the antivirus program, but unfortunately, it's still not working. I've also made another video, maybe there's something noticeable in it, but I doubt it. I will cry if this doesn't work for me, as I've been waiting so long for the release

Link to the Video: https://www.youtube.com/watch?v=q3XmMXLd8PI

**Comment by praydog** [comment]
> Thank you, Praydog, for your awesome support. But, unfortunately, I have to say it's not working. Absolutely nothing has changed. I've now also placed euvr directly under C:\uevr\ and turned off the antivirus program, but unfortunately, it's still not working. I've also made another video, maybe there's something noticeable in it, but I doubt it. I will cry if this doesn't work for me, as I've been waiting so long for the release
> 
> Link to the Video: https://www.youtube.com/watch?v=q3XmMXLd8PI
> 
> @JonkHunkle Unreal engine 4.27 is the last version of UE 4. So its not a early version because UEVR supports from 4.09 to the last version.

Can you take a screenshot of the directory that UEVR is in so I can see all the files?

**Comment by JonkHunkle** [comment]
> Thank you, Praydog, for your awesome support. But, unfortunately, I have to say it's not working, with 1.01 release. Absolutely nothing has changed. I've now also placed euvr directly under C:\uevr\ and turned off the antivirus program, but unfortunately, it's still not working. I've also made another video, maybe there's something noticeable in it, but I doubt it. I will cry if this doesn't work for me, as I've been waiting so long for the release
> 
> Link to the Video: https://www.youtube.com/watch?v=q3XmMXLd8PI
> 
> @JonkHunkle Unreal engine 4.27 is the last version of UE 4. So its not a early version because UEVR supports from 4.09 to the last version.

according to the documentation uevr supports version 4.8-5.2?

**Comment by therealnova** [comment]
Here is the screenshot
![folder](https://github.com/praydog/UEVR/assets/28540686/ca6227fa-3792-4e20-aebb-bbf41f851742)

**Comment by JonkHunkle** [comment]
> @praydog Here is the screenshot ![folder](https://private-user-images.githubusercontent.com/28540686/293769394-ca6227fa-3792-4e20-aebb-bbf41f851742.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMjM3OTIsIm5iZiI6MTcwNDIyMzQ5MiwicGF0aCI6Ii8yODU0MDY4Ni8yOTM3NjkzOTQtY2E2MjI3ZmEtMzc5Mi00ZTIwLWFlYmItYmJmNDFmODUxNzQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE5MjQ1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMmEyYmNmYWE1ZTZiNDA0NjI0ZjlhNGY5ZTY5Y2QxOWJkZTBmYWJjOWMyYjQyMjhjZTkyM2VkZGJiNmFiODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lSz_-NRJOfdRw3-odvPpTEfKQt06w6CljuG-PExrvmE)
> 
> @JonkHunkle If I haven't misunderstood you, you're mixing something up. UE 4.8 is not 4.80 but 4.08. It's a bit foolishly written by Unreal. So, Unreal Engine 4 ranges from 4.00 to 4.27.


thanks! is it just me or is that a unnecessarily confusing way to version your stuff lol

**Comment by transdodo** [comment]
> @praydog Here is the screenshot ![folder](https://private-user-images.githubusercontent.com/28540686/293769394-ca6227fa-3792-4e20-aebb-bbf41f851742.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMjQ4NzIsIm5iZiI6MTcwNDIyNDU3MiwicGF0aCI6Ii8yODU0MDY4Ni8yOTM3NjkzOTQtY2E2MjI3ZmEtMzc5Mi00ZTIwLWFlYmItYmJmNDFmODUxNzQyLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE5NDI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk0NWNiYjkxODQxZWY0Mzk4OWEyYmI5MzQ2NGY4OWZkYWM2MGU1YzQ0NjZhNzk3YWVmYzlhODg1ODEzZTYwMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EgRYqnn-5hJc4jjrns5RbYBLrcVRRMOM0_OAUCMKjW8)
> 
> @JonkHunkle If I haven't misunderstood you, you're mixing something up. UE 4.8 is not 4.80 but 4.08. It's a bit foolishly written by Unreal. So, Unreal Engine 4 ranges from 4.00 to 4.27.

Any solutions ?

**Comment by therealnova** [comment]
@praydog I've found my mistake. While downloading, my antivirus program (Kaspersky) deleted the UEVRBackend.dll from the .zip file without notifying me. Now, with that file, Tropico 6 works out of the box with the injector. I hope this solution can help others. I'm sorry for taking up your time with such a silly mistake.

**Comment by JonkHunkle** [comment]
@therealnova NICE! i see i have the same issue. hopefully this is the fix i need

**Comment by JonkHunkle** [comment]
fixed! thanks @therealnova

**Comment by Aliput** [comment]
> @praydog I've found my mistake. While downloading, my antivirus program (Kaspersky) deleted the UEVRBackend.dll from the .zip file without notifying me. Now, with that file, Tropico 6 works out of the box with the injector. I hope this solution can help others. I'm sorry for taking up your time with such a silly mistake.
> 
> @transdodo My solution was that there must be 1 folder and 9 files in the main injector folder, as can be seen in my screenshot.
> 
> ![folder4](https://private-user-images.githubusercontent.com/28540686/293785337-a6744e00-3cad-45d5-b741-1a59fb13004d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzMDU4ODYsIm5iZiI6MTcxMTMwNTU4NiwicGF0aCI6Ii8yODU0MDY4Ni8yOTM3ODUzMzctYTY3NDRlMDAtM2NhZC00NWQ1LWI3NDEtMWE1OWZiMTMwMDRkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI0VDE4Mzk0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwYmEwMWU1ZjM3ODE5ZTIxMmNiZDhmMzRiZTE5M2UzY2M2ODA5ZWViNWIxZWI1ODhhYzhlNGMzMjA1ZDNkMTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zfgFFYTWZb6JJJe0MxRTMfu-zc2tJhC4EEUR5twgIzk)

SO HOW DO YOU STOP YOUR ANTI VIRUS FROM DELETING ON DOWNLOAD?!! I can't turn mine off and in the zip file the backend.dll is still there but it won't copy accross to a new folder?
