### ISSUE TITLE
[ERROR] EUVRBackend.dll error-  Error status 0xc000012f

### ISSUE THREAD

**Issue by Phor8** [praydog/UEVR#171]
Every time I try to inject into an unreal engine game in the background, I get a pop up with this error. The dll file is still in the UEVR folder and hasn't been deleted by antivirus. screenshot below of folder files

I've followed what information i could about this issue from people having the problem without any VR modding being done, but im only getting this when trying to inject the VR goodness. Checked my image health in Command Prompt:
No component store corruption detected. and sfc checks all good.

Happens on all Unreal Engine games ive tried to run from Xbox Game Pass (Roboquest, Lies of P, PalWorld) or Epic (Vampyre), though Steam games dont show up on the drop down menu for injection. Tried both OpenVR or OpenXR. 

Using Quest 1 with official oculus link cable
 - windows 11
 - RX 5700 XT
 - AMD Ryzen 5 3500X (updated drivers)
 
Heres while running PalWorld in the background
![Screenshot 2024-01-26 224031](https://github.com/praydog/UEVR/assets/157770123/c032ca22-8ef2-43d4-a23a-19f29a22752e)
heres the config for the roaming data if relevant at all
VR_UncapFramerate=true
VR_SyncedSequentialMethod=1
VR_RenderingMethod=0
VR_Compatibility_SkipPostInitProperties=false
Frontend_RequestedRuntime=openvr_api.dll

![Screenshot 2024-01-26 233949](https://github.com/praydog/UEVR/assets/157770123/20eded13-60eb-4926-9a24-08ad595a7287)

thanks for any assistance

**Comment by praydog** [comment]
Try re-downloading UEVR fresh, and extract it to an entirely different folder than where you put it.

**Comment by Phor8** [comment]
ah okay. simple enough seemed to fix it when i re-downloaded it and extracted in a different location
thanks for the assistance
