### ISSUE TITLE
[UDS] recognized

### ISSUE THREAD

**Issue by GalaxyOfZero** [praydog/UEVR#174]
The Anti Virus detect a Trojan in the mod DLL
![image](https://github.com/praydog/UEVR/assets/57020876/36e39cef-4d17-4974-be41-538d39cd0f16)

**Comment by DeepBlue27** [comment]
same here: 
![image](https://github.com/praydog/UEVR/assets/19731251/d6244a25-d924-4831-867b-6076983d6f1e)

**Comment by praydog** [comment]
Duplicate issue
