### ISSUE TITLE
Automaticall tick on the virtual desktop fix

### ISSUE THREAD

**Issue by djsolidsnake86** [praydog/UEVR#179]
I always use virtual desktop, and every time i must tick the option virtual desktop fix, also many times that option return to off, is possible set a option for have it always on when using virtual desktop? thanks

**Comment by praydog** [comment]
It only needs to be ticked on when using SteamVR as the OpenXR runtime in particular, it doesn't need to be on with VDXR. Are you using VDXR or SteamVR?

**Comment by djsolidsnake86** [comment]
> It only needs to be ticked on when using SteamVR as the OpenXR runtime in particular, it doesn't need to be on with VDXR. Are you using VDXR or SteamVR? It also turns on automatically when using SteamVR.

i use vdxr, seem that enabling it help a very little

**Comment by praydog** [comment]
Closing this then, as there is no reason for it to be on with VDXR. Unless you can point out any issues with it in VDXR.
