### ISSUE TITLE
Spacebourne2 UI fix

### ISSUE THREAD

**Issue by Dazta33** [praydog/UEVR#186]
Are you able to make it compatible with the UI on that game?  It works so well in VR. Such a shame the UI isn't functonal with UEVR injected

**Comment by praydog** [comment]
UI seems functional with the newly added `AHUD UI Compatibility` option under the `Compatibility` tab in the [UEVR Nightly builds](https://github.com/praydog/uevr-nightly/releases/latest). Advanced options must be enabled to see it.
