### ISSUE TITLE
[BUG]Giraffe and Annika - crash when inject

### ISSUE THREAD

**Issue by KwaiBird** [praydog/UEVR#188]
Game Title: Giraffe and Annika
https://store.steampowered.com/app/1122100/_/

**Describe the bug**
I have tried via both Virtual Desktop(VDXR, openXR) and Steam VR(OpenVR/OpenXR) but it was failed. When I tried to inject UEVR to the game, it was crashed immediately with Unreal Engine 4 Crash Reporter. 

- added -nohmd to the game's command
- changed VR_renderingMethod to Synced Sequential
- checked VR_Compatibility_SkipPostInitPr..... on the UEVR frontend
- unchecked VR_UncapFramerate
- Run UEVR as administer

[on Unreal Engine 4 Crash Reporter]
Unhandled exception

KERNELBASE
UEVRBackend
UEVRBackend
UEVRBackend
UEVRBackend
UEVRBackend
UEVRBackend
UEVRBackend
UEVRBackend
UEVRBackend
kernel32
ntdll

UEVR Beta 1.03 / Nightly 767
Virtual Desktop Streamer 1.30.1
Steam VR beta 2.3.5
SteamLink v.2.0.4.683
Virtual Desktop 1.30.1
Meta Quest 3 software ver. 49829370048400510

**PC Specs :**
 - OS: Windows 10 Home 22H2
 - Graphics card: MSI Radeon RX 6600 XT GAMING X 8G
 - CPU: AMD Ryzen 9 5900X
 - Headset Model: Meta Quest 3
 - OpenXR or OpenVR: OpenXR(Virtual Desktop, SteamVR) / OpenVR(Steam VR)
 - Streamer if applicable: Virtual Desktop, Steam Link
 - If using OpenXR, the runtime: SteamVR, VDXR
 
[UE4CC-Windows-8F7644D64074AED675C8048236EE5600_0000.zip](https://github.com/praydog/UEVR/files/14203979/UE4CC-Windows-8F7644D64074AED675C8048236EE5600_0000.zip)
[Giraffe_and_Annika-Win64-Shipping.zip](https://github.com/praydog/UEVR/files/14203939/Giraffe_and_Annika-Win64-Shipping.zip)

**Comment by praydog** [comment]
It looks like it's crashing when attempting to get the path to the global config in %APPDATA%. Likely because there are strange characters in the path I think. Are other games okay? This game seems to work fine for me but I will still look into this issue

**Comment by KwaiBird** [comment]
Thank you.Your guess is correct.
These characters are Japanese.Some Japanese games use the characters for the path.
So I rename the path from
C:/Program Files (x86)/Steam/steamapps/common/Giraffe and annika（ジラフとアンニカ）/Giraffe_and_Annika/Binaries/Win64/
to
C:/Program Files (x86)/Steam/steamapps/common/Giraffe and annika/Giraffe_and_Annika/Binaries/Win64/
,then I can inject UEVR to the game without crashing.
I guess the path with other Asian characters such as Chinese and Korean ones cause same trouble.
 Other games I have tried are okay.

**Comment by KwaiBird** [comment]
Sure. The newest nightly works fine with the original characters in the filepath. The crash goes away.Thank you again.

**Comment by KwaiBird** [comment]
Sorry for reopen. If I choose OpenXR with SteamVR/Virtual Desktop, UEVR the newest nighty in the game shows No runtime loaded message. And the frontend does not handle Japanese characters correctly.It supposed to show "C:/Program Files (x86)/Steam/steamapps/common/Giraffe and annika（ジラフとアンニカ）/Giraffe_and_Annika/Binaries/Win64/" as I wrote above.
Attempt to Reinitialize does not work.
![frontend](https://github.com/praydog/UEVR/assets/122966109/87aeeb6d-cf19-4704-8176-cca80d27d1f6)
![game](https://github.com/praydog/UEVR/assets/122966109/dc283db4-aa26-4b61-b921-d572c7113c4a)

If I choose OpenXR as runtime, it is okay.
I have tried other game, The Forgotten City, with OpenXR choosed for both SteamVR and VD, it works.

**Comment by praydog** [comment]
Try the latest nightly again

**Comment by praydog** [comment]
Now newest build should also display the path correctly in the injector UI

**Comment by KwaiBird** [comment]
Great. UEVR Nightly 771 fixes both issues.
- The injector UI displays the path correctly
- OpenVR with SteamVR( and Virtual Desktop with SteamVR) works
- OpenXR with SteamVR and Virtual Desktop works

Now I can close the issue again. Thank you.
