### ISSUE TITLE
[BUG] Savage planet

### ISSUE THREAD

**Issue by JibJab1980** [praydog/UEVR#189]
Hi there lovong the mods thank you so much

I'm struggling with savage planet on my pico 4, 3080 ti. The background and objects move around when I move my head with strange artifacts and big jagged edges. 
I've tried all 3 render methods, all in game graphic setting, all in game antialiasing mehods and tried with vd wireless pico streaming assistant wired. 
Such a shame as I can see the game seems built for vr.
Any suggestions would be hugely appreciated.

**Comment by praydog** [comment]
Game specific issues are not meant to be here unless they are crashes I can look at or it seems to be more of a generic issue I could fix that can propagate to other games. You should use the Flat2VR Discord for this.

This also sounds like something symmetric projections will fix in the future.

**Comment by praydog** [comment]
Likely duplicate issue #163
