### ISSUE TITLE
integrate UEVR into my game

### ISSUE THREAD

**Issue by ytyyt1** [praydog/UEVR#19]
I am an indie game developer and I am currently working on a horror game. Since I have no experience in VR development, it would be my dream to give players the choice of VR MODE.

So: I'm thinking about integrating UEVR into the game and packaging it together. Can I do this with the appropriate credit?

If that's possible, I'm curious if there's anything I can set up in the Unreal project (such as automatic startup) to give players a more seamless VR experience.

**Comment by praydog** [comment]
No. This is not the intended use. You have much more tools at your disposal to do this better using official UE tools. If you really feel the need to, then you can link to the repository.
