### ISSUE TITLE
The ExamplePlugin dll installation fails with Minor release error.

### ISSUE THREAD

**Issue by MaslowCorporation** [praydog/UEVR#190]
Hi, my problem is simple. I'm trying to get into plugin development for UEVR, specifically for Grand Theft Auto Trilogy Definitive Edition. And I'm also trying to make a Github Repo describing the process.

But my compiled C++ plugin fails to execute when I load it in UEVR. The error is about:

```
This requires a newer minor version
``` 

This error doesn't crash UEVR or the game, it is just an error message in the UEVR in-game menu, in the plugin section. But it means the plugin is not working.

Here's the URL of the Github repo, containing the UEVRPlugin.cpp plugin file I'm trying to create, and it's C++ dependencies.

https://github.com/MaslowCorporation/GTA-SAN-ANDREAS-VR

So I'm trying to compile the example C++ plugin code 

(UEVRPlugin.cpp in the provided repo) 

```
#include <memory>

#include "uevr/Plugin.hpp"

using namespace uevr;

#define PLUGIN_LOG_ONCE(...)                   \
    {                                          \
        static bool _logged_ = false;          \
        if (!_logged_)                         \
        {                                      \
            _logged_ = true;                   \
            API::get()->log_info(__VA_ARGS__); \
        }                                      \
    }

class UEVRPlugin : public uevr::Plugin
{
public:
    UEVRPlugin() = default;

    void on_dllmain() override {}

    void on_initialize() override
    {
        // Logs to the appdata UnrealVRMod log.txt file
        API::get()->log_error("%s %s", "Hello", "error");
        API::get()->log_warn("%s %s", "Hello", "warning");
        API::get()->log_info("%s %s", "Hello", "info");
    }

    void on_pre_engine_tick(UEVR_UGameEngineHandle engine, float delta) override
    {
        PLUGIN_LOG_ONCE("Pre Engine Tick: %f", delta);
    }

    void on_post_engine_tick(UEVR_UGameEngineHandle engine, float delta) override
    {
        PLUGIN_LOG_ONCE("Post Engine Tick: %f", delta);
    }

    void on_pre_slate_draw_window(UEVR_FSlateRHIRendererHandle renderer, UEVR_FViewportInfoHandle viewport_info) override
    {
        PLUGIN_LOG_ONCE("Pre Slate Draw Window");
    }

    void on_post_slate_draw_window(UEVR_FSlateRHIRendererHandle renderer, UEVR_FViewportInfoHandle viewport_info) override
    {
        PLUGIN_LOG_ONCE("Post Slate Draw Window");
    }
};

// Actually creates the plugin. Very important that this global is created.
// The fact that it's using std::unique_ptr is not important, as long as the constructor is called in some way.
std::unique_ptr<UEVRPlugin> g_plugin{new UEVRPlugin()};

```

into a .dll file using this command

```
g++ -std=c++20 
-shared -o UEVRPlugin.dll -I include UEVRPlugin.cpp
```

I'm on Windows 10, and I installed MinGW

I can successfully generate the .dll file. it is there in the Github repo I provided.

But when I try to install this dll plugin in the plugins/ folder of GRand Theft Auto SA, I get an error, or rather a error message, in UEVR, complaining about The minor version needing to be upgraded.

I added the game-specific folder containing the game logs and such, as a SanAndreas.zip file in the github repo provided

Help me ;-) Thx

**Comment by praydog** [comment]
Use the nightly version or compile it yourself, the plugin API does not match the current latest release. You will need to either use the nightly version or grab the include folder from the 1.03 tag.

https://github.com/praydog/UEVR-nightly

**Comment by praydog** [comment]
Also GCC is not tested. Make sure it has the same MSVC calling convention (rcx, rdx, r8, r9)

**Comment by MaslowCorporation** [comment]
Can you give me the appropriate command I need to run in order to compile the plugin. Sorry if i'm bothering you with my noob inquiries. I will install the required stuff on my own, I just need a command that works properly ;-)

**Comment by MaslowCorporation** [comment]
Nevermind, I fixed the issue thanks to your explanations. You should add these instruction to UEVR docs, it'll help MANY people trying to create stuff. I almost gave up trying, because I tried for 2 days straight using different compilers, what fixed the issue is to grab the include folder from the latest tag (1.03 tag), on the https://github.com/praydog/UEVR/releases page. Please add this clarification to this page, to prevent future headaches to aspiring modders 

https://praydog.github.io/uevr-docs/plugins/getting_started.html

thank you !!!!!
