### ISSUE TITLE
[BUG]Atomic Heart crashes with objecthook after latest patch

### ISSUE THREAD

**Issue by SpanielGarrison** [praydog/UEVR#191]
Atomic Heart was working fine up to 7 February.  On 8 February a patch was installed on Steam (see uploaded screenshot).  After that ,injecting UEVR causes the game to crash either (i) upon injection if there is a profile with saved objecthooks in place; or (ii) if there is no profile with saved objecthooks, the game crashes as soon as you click on the objecthook menu in the UEVR UI.  The crash reports attached to this bug report are examples of the second scenario.  From other users in the Discord it looks like the problem might not be affecting gamepass versions of the game (mine is Steam version)

**Upload logs and any crash dumps**
[AtomicHeart-Win64-Shipping.zip](https://github.com/praydog/UEVR/files/14227066/AtomicHeart-Win64-Shipping.zip)

Game-specific crash dumps:
[Crashes.zip](https://github.com/praydog/UEVR/files/14227067/Crashes.zip)

**Identify the UEVR version**

Version 1.03 Nightly build from 5 or 6 February 

**To Reproduce**

Start game
Put on headset
Inject [will then crash if there is a profile with objecthooks, if not:]
Go to UEVR UI and click on objecthook menu - game then crashes

**Screenshots**

![image](https://github.com/praydog/UEVR/assets/159588396/29c457f6-ff6f-4192-a775-2d09bb7f883b)
![image](https://github.com/praydog/UEVR/assets/159588396/7652215d-0337-47bd-a9bc-2b6b46e6e9b4)

**PC Specs (please complete the following information):**
 - OS:  Windows 11)
 - Graphics card: RTX 4090 (no overclock)
 - CPU: i9-13900k (no overclock)
 - Headset Model: Quest 3
 - OpenXR or OpenVR: OpenXr
 - Streamer if applicable: Virtual desktop 
 - If using OpenXR, the runtime: VDXR

Thank you for taking the time to look into this, I am very grateful.  Atomic Heart is such a great game in VR!

**Comment by mrbelowski** [comment]
Note that the demo doesn't appear to crash like this

**Comment by praydog** [comment]
Fixed in
ef68b854db04abe74cf577f4d4a5a8c1a7e448fb
3997108934a41fdbb1c6a6e8ff59d7fcd63362ac
https://github.com/praydog/UESDK/commit/48810d172e43e1d0760538ef2673f75f141b0f46

Download from [Nightly builds](https://github.com/praydog/UEVR-nightly)
