### ISSUE TITLE
How to set breakpoints in a C++ UEVR plugin ?

### ISSUE THREAD

**Issue by MaslowCorporation** [praydog/UEVR#194]
Hi, my question is simple.

How to set breakpoints in a C++ UEVR plugin ?

I would like to be able to set breakpoints in my code, or in some way, with the .pdb file.

How do I do this, so I can examine the code at runtime, when the plugin is loaded.

Thanks.

**Comment by praydog** [comment]
Attach a debugger before injecting.

**Comment by MaslowCorporation** [comment]
I should attach the debugging to what process ? the game or the UEVR instance
