### ISSUE TITLE
Hello I Have UE4 Extraktor for you

### ISSUE THREAD

**Issue by Soliver84** [praydog/UEVR#197]
Hello If you need this there is an unpacker for UE4
[UE4PakUnpacker.zip](https://github.com/praydog/UEVR/files/14318886/UE4PakUnpacker.zip)

**Comment by kolardavid** [comment]
First of all, not an issue and not really relevant to UEVR. I believe you mean it good, but source of this software is unknown and virustotal detects it as a virus (maybe false positive, but this tool shouldn't do any hacky stuff, so even false positive seems weird here).

Anyway I recommend everyone to avoid such tool. There is no need for tool for unpacking UE files, you can use official UnrealPak.exe from corresponding engine version.
