### ISSUE TITLE
cant download cuz gives me virus warnings [BUG]

### ISSUE THREAD

**Issue by FroofyFroof** [praydog/UEVR#199]
why are you trying to hack my computer wtf

**Comment by john-clark** [comment]
Been that way for a while. Here is the report on the old version.

https://www.virustotal.com/gui/file/338514f37beb80cebe94e29af7185a7e020e359636a88e9e11fff76c04f7a293

**Comment by praydog** [comment]
Duplicate issue #79

**Comment by BananaAcid** [comment]
I just redid the check, the warnings have doubled ...

https://www.virustotal.com/gui/file/527e9f92474e4915bfdd0b0b7bbbd45a075941c682e734ceb920d0d329942b1e
