### ISSUE TITLE
PAYDAY 3 UE Version 4.27 Crash

### ISSUE THREAD

**Issue by Booo3** [praydog/UEVR#20]
Game Crashes When Touching any keys on the controller.

On OpenVR and OpenXR

[log.txt](https://github.com/praydog/UEVR/files/13806934/log.txt)

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0xffffffffffffffff

PAYDAY3Client_Win64_Shipping
UEVRBackend
UEVRBackend
UEVRBackend
UEVRBackend
UEVRBackend
UEVRBackend
UEVRBackend
UEVRBackend
PAYDAY3Client_Win64_Shipping
PAYDAY3Client_Win64_Shipping
PAYDAY3Client_Win64_Shipping
PAYDAY3Client_Win64_Shipping
UEVRBackend
UEVRBackend
PAYDAY3Client_Win64_Shipping
PAYDAY3Client_Win64_Shipping
PAYDAY3Client_Win64_Shipping
UEVRBackend
UEVRBackend
PAYDAY3Client_Win64_Shipping
PAYDAY3Client_Win64_Shipping
PAYDAY3Client_Win64_Shipping
PAYDAY3Client_Win64_Shipping
PAYDAY3Client_Win64_Shipping
PAYDAY3Client_Win64_Shipping
kernel32
ntdll

**Comment by praydog** [comment]
Upload any crash dumps you can find inside `%LOCALAPPDATA%\PAYDAY3\Saved`

**Comment by praydog** [comment]
Likely fixed in 53d6a13366b68743202df41514cc4e7cb4965e16

**Comment by arnaud-blomme** [comment]
still happen with latest

**Comment by praydog** [comment]
> still happen with latest
> 

Use the nightly build. https://github.com/praydog/uevr-nightly/releases/latest
