### ISSUE TITLE
[BUG]Spirit of the North on epic, fog on the right eye

### ISSUE THREAD

**Issue by jadmanxxx** [praydog/UEVR#201]
the game worke great, but on level 2 there white fog only on the right eye, how can i fix this ?
the game have no Option do deactivate fog in game

**Comment by praydog** [comment]
Synchronized sequential rendering method

**Comment by jadmanxxx** [comment]
sorry, how do I do that?

**Comment by praydog** [comment]
In the in game UEVR menu under "Unreal"
