### ISSUE TITLE
[BUG] Quest Pro Thumbrest DPad Shifting not working

### ISSUE THREAD

**Issue by feuerball11** [praydog/UEVR#205]
**Describe the bug**

Hi :-) 
I'm playing Pacific Drive on the latest nightly build. I do have a Quest Pro. I noticed that the option for DPad SHifting with the thumb rest does not appear to be working. 

UEVR-specific logs and crash dumps:

[PenDriverPro-Win64-Shipping.zip](https://github.com/praydog/UEVR/files/14393022/PenDriverPro-Win64-Shipping.zip)

**Identify the UEVR version**

UEVR Nightly 801 (c50a11a2bd835a69f482924e18963d100fbcfd52)

**To Reproduce**

1. Set DPad Shifting to Thumprest + Stick on Quest Pro 
2. Notice that whatever you try, you cant get dpad inut to work

**Expected behavior**

DPad input working with Quest Pro Controller

**PC Specs (please complete the following information):**
 - OS Windows 11
 - Graphics card: GTX 4090
 - i5-13600KF
 - Quest Pro
 - OpenVR
 - Quest Link Via Steam VR

**Comment by praydog** [comment]
Does not work on OpenVR, you must use OpenXR.
