### ISSUE TITLE
[BUG] OpenXR could not create openxr instance-32

### ISSUE THREAD

**Issue by KeksNino** [praydog/UEVR#219]
**Describe the bug**

When i try to inject UEVR into a game with OpenXR it says: OpenXR not loaded: could not create openxr instance -32.
It also says OpenVR not loaded: openvr_api.dll not found. I never had this issue before and suddenly its just there. I also had the problem that Beat Saber doesnt hook to vr anymore, maybe this has something to do with it. I already tried reinstalling steamvr.
The problem occurs with all games. And when i try to inject with OpenVR it says: OpenXR not loaded: Could not load openxr_loader.dll and OpenVR not loaded: VR_Init failed: Hmd Not Found Presence Failed (126)

**Upload logs and any crash dumps**

If this is a game crash or game bug:

game bug

UEVR-specific logs and crash dumps:
[Ghostrunner2-Win64-Shipping.zip](https://github.com/praydog/UEVR/files/14549774/Ghostrunner2-Win64-Shipping.zip)

Game-specific crash dumps:

[Logs.zip](https://github.com/praydog/UEVR/files/14549771/Logs.zip)

**Identify the UEVR version**

Beta 1.03

**To Reproduce**

1. See logs

**Expected behavior**

No errors and hooking to vr.

**Screenshots**
![image](https://github.com/praydog/UEVR/assets/87879013/959ec88f-788a-4e07-9682-556c2d669f2f)
![image](https://github.com/praydog/UEVR/assets/87879013/eace5797-0998-4cd1-8024-7826a0b67cca)

**PC Specs (please complete the following information):**
 - Widnows 10
 - Geforce RTX 3060
 - Amd Ryzen 5 3600x
 - Meta Quest 3, Meta Quest 2
 - OpenXR and OpenVR
 - Air Link, Steam Link
 - Oculus, SteamVR

**Comment by KeksNino** [comment]
fixed it, the problem was the reshade steamvr plugin but i removed and it works now

**Comment by AlexMilovano** [comment]
friend, could you describe in more detail what exactly you did. I'm facing the same problem and I can't solve it. I scoured the entire Internet in search. I need the game to run not on a flat screen, but in full VR mode. and it works for openVR without problems. But for openXR the UEVR application gives errors. And I just can’t get it to work on anything other than a flat screen.

**Comment by AlexMilovano** [comment]
Can you tell me where this plugin is located? I only used the reshade program for a long time, not a plugin. Now I found 1 tip to delete the C:\ProgramData\Reprise folder. is this what you are talking about? or something else. This is exactly what I am going to check now. Thanks for the quick response! I appreciate it.

**Comment by AlexMilovano** [comment]
YES, THIS IS IT. IT WORKED. IF THIS HELPES ANYONE, KNOW THAT YOU JUST NEED TO DELETE THIS FOLDER.
