### ISSUE TITLE
Street Fighter 5 crashes after injection

### ISSUE THREAD

**Issue by InitialXKO** [praydog/UEVR#230]
After injection, the computer screen will display the UEVR interface frame menu as normal, but after a few seconds, when the VR initialization is complete, the game will automatically close.
By the way, if you inject it without connecting to VR, the game won't crash. But when you connect to VR and click the reinitialize button, the game will crash immediately when the openxr or openVR dll is loaded.

**Comment by praydog** [comment]
Game is too old

**Comment by praydog** [comment]
Might get around to older games in the future, so any of those old games will be covered under that umbrella

**Comment by YorhaX2P** [comment]
> Might get around to older games in the future, so any of those old games will be covered under that umbrella

I'm glad you could do this in the future <3

Street Fighter V uses UE 4.6 on PS4 and PC are the same, but PS4 is full of unencrypted PAKS. it's fun to port PC to PS4 for modding :)
