### ISSUE TITLE
[BUG] Not really a bug, but huge QoL: Download gets blocked, Virus detection

### ISSUE THREAD

**Issue by randomVRguy** [praydog/UEVR#233]
Nothing new, but I experienced again with v1.04 and I think this certainly holds back some people from using it. 

1) The latest Chrome browser does completely block the download of the UEVR.zip (this was not the case before). You have to disable ALL security settings to find it in your downloads folder, _then_
2) Windows tells you that it contains definitely a virus. You must disable all Windows security features and set up an exception to do anything with it

Sure, for experienced users the topic isn't worth mentioning, but every newcomer is put off badly by that and some won't go any further at this point....

**Comment by praydog** [comment]
Duplicate issue #79
