### ISSUE TITLE
[BUG] Nothing to inject to in dropdown menu

### ISSUE THREAD

**Issue by 4ngryB0b** [praydog/UEVR#239]
Salut Praydog!

Thanks for the effort to create such a great app. Hopefully I will be able to run it one day.
Trying since version 1.02. Now on 1.04. 

**Describe the bug**
Nothing appears in the UEVR dropdown menu I could inject to.

What I do:

- Fight my Windows defender not to delete UEVR.zip on moment of download
   (Copy content of UEVR.zip to HDD and mark UEVR folder and injector.exe file as exception in Windows defender)

- Connect Meta Quest 3 and run Oculus App and Quest Link (My first choice. But also tried Steam Link and Virtual Desktop)

- Starting UEVR as Administrator

- Starting Insurgency Sandstorm with custom arguments ( -insecure -NoEAC)

- Alt Tab to UEVR
  Problem: Nothing appears in the dropdown menu I could Inject to. Switching VR to XR changes nothing.

  Exception:
- Windows security Service appears in the dropdown menu when I leave it open. (after the fight for the UEVR.zip to download)
   Of coures I do not inject into this.
-  When running Raipal (on UEVR 1.02) i can inject into Raipal. (No I dont inject into Raipal)

What am I doing wrong? Noone seems to have this problem across the entire damn internet.
The content of UEVR is intact. It does not get deleted by windows defender - I checked 179 times!

Any help or hint is welcome. Im really keen on trying UEVR with Insurgency for a while now. 
(I don't own other unreal games to try out but L4D2 and Doom 3 run great in VR with other methods)

Thanks in advance!
 
If this is a game crash or game bug:
/

UEVR-specific logs and crash dumps:
/

Game-specific crash dumps:
/

**Identify the UEVR version**
1.02 / 1.04 I skipped 1.03

**To Reproduce**
Any day, any runtime blank dropdown menu!

**Expected behavior**
I want the Process/game (Insurgency Sandstorm) to appear in the dropdown menu of UEVR

**Screenshots**
/

   PC SPECS:
 - Windows 10
 - RTX 3070 Ti
 - Core I7 6700K, some RAM
 - Meta Quest 3
 - OpenXR / OpenVR tried with Quest link, Steam Link, Virtual Desktop

**Comment by praydog** [comment]
It means you aren't actually running your game without EAC. -NoEAC is not a real command line argument. You need to start your game directly from its executable in the game folder.

**Comment by 4ngryB0b** [comment]
Thanks for your help! 
NoEAC was indeed bullshit 3rd party knowledge! Sorry for bugging you with game specific crap.
