### ISSUE TITLE
[BUG] after playing a game with uevr, the gpu wont go in idle state and consume more wattage til the restart of pc

### ISSUE THREAD

**Issue by djsolidsnake86** [praydog/UEVR#242]
i found a problem in the uevr mod, after using it, the gpu frequence of core and memory doesn't go in idle state, so the gpu consume more watt in idle (35 watt while should consume about 3-5 watt), is a waste of energy and money, and gpu fans works while should stay stop in idle
my gpu is a rtx 4070ti

i dont have this problem after playing native vr games, flat games, or after seeing movies or whatelse
pay attention if you have this problem, you can see consumption of gpu with hwinfo64 or gpuz

**Comment by mark-mon** [comment]
What is your OS?
What is your HMD?
How is your headset connected?
What injection options?
Give a list of games you play to reproduce this?

**Comment by djsolidsnake86** [comment]
> What is your OS? What is your HMD? How is your headset connected? What injection options? Give a list of games you play to reproduce this?

windows 10, quest 3, connected via quest link, openxr
everytime i use uevr with games happen this problem, the only solution for make work the gpu with idle frequency and with fanstop is to restart pc

**Comment by mark-mon** [comment]
I couldn't reproduce this. Played persona 3 for 2 hours and after exiting, GPU is sitting at 0.875 watts idle.

I don't think it's a bug in UEVR.
