### ISSUE TITLE
Jedi Fallen Order Crashes When Using Injector

### ISSUE THREAD

**Issue by jaydough76** [praydog/UEVR#244]
Has anyone else run into this issue?  I launch Jedi Fallen Order and then when i launch the injector the headset first goes completely dark, and then the game crashes.
I'm running on Virtual Desktop where i have OpenXR Runtime set to VDXR on the Virtual Desktop Streamer.

**Comment by praydog** [comment]
Use synchronized sequential rendering

**Comment by zachtos** [comment]
same here, I gave up on trying to play.  HTC vive pro2 with xbox elite controller.  I tried steamVR and openXR and still just crash.  I'm not even sure if the UEVR profile helps or not.
