### ISSUE TITLE
Add the ability to completely disable VR

### ISSUE THREAD

**Issue by Aeyth8** [praydog/UEVR#257]
Crazy right? Why disable VR on a VR-orientated program? 
Short answer is its extremely useful for other things debug and reverse engineer related, and I'm sick of having to emulate a HMD just to get it to work.

**Describe the solution you'd like**
What I ask is for you to implement that as a checkbox, the problem at hand is that if you do not inject VR, it will say "Waiting for UObjectBase to be hooked...."

So please hook it without waiting for the OpenVR and OpenXR.

Thank you

**Comment by praydog** [comment]
Use UE4SS

**Comment by Aeyth8** [comment]
Doesn't work
