### ISSUE TITLE
[VIRUS] PUA:Win32/Packunwan Virus found in UEVR.zip  

### ISSUE THREAD

**Issue by QuantD-VAM** [praydog/UEVR#259]
Windows11 is isolating the UEVR ZIP File because it contains a Virus. Here are the details:

PUA:Win32/Packunwan
file: H:\Installs\UEVR.zip->UEVRBackend.dll

webfile: H:\Installs\UEVR.zip|https://objects.githubusercontent.com/github-production-release-asset-2e65be/531307134/2277f4f4-6212-4ad9-980e-2cbdd23dd4ad?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetproduction%2F20240703%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20240703T112708Z&X-Amz-Expires=300&X-Amz-Signature=f14d2d330ee5a3c1930001d16ea89e697d7e1647384423578a9af7dffcfdd264&X-Amz-SignedHeaders=host&actor_id=0&key_id=0&repo_id=531307134&response-content-disposition=attachment%3B%20filename%3DUEVR.zip&response-content-type=application%2Foctet-stream|pid:18720,ProcessStart:133644796508607386

1. Go to UEVR Download: [https://github.com/praydog/UEVR/releases]
2. Click on Just looking for the download? Here: https://github.com/praydog/UEVR/releases/latest/download/UEVR.zip
3. Windows11 will immediately come up with an Virus alert

**Comment by praydog** [comment]
Duplicate issue #79
