### ISSUE TITLE
Missing .NET installation

### ISSUE THREAD

**Issue by Alex180689** [praydog/UEVR#26]
Hi!
When I try to run UEVRInjector.exe an error message pops up saying:
You must install .NET Desktop Runtime to run this application 

Architecture: x64
App host version: 6.0.25
Would you like to download it now?

I tried installing it, but the error still appears. 
I can confirm .NET was installed successfully from cmd

![Immagine 2024-01-02 160422](https://github.com/praydog/UEVR/assets/91917666/766e10e2-eb2a-405f-bb52-553dc2c58d8d)

I can see the correct version in regedit too

![image](https://github.com/praydog/UEVR/assets/91917666/945fd742-ebaa-4427-8249-898387bf6397)

**Comment by Alex180689** [comment]
Solved: the path of a system variable was not pointing to the .NET installation directory

**Comment by AceRimmer76** [comment]
Apparently I am having issues installing .NET 6.0.25 as well.  What do you mean by " the path of a system variable was not pointing to the .NET installation directory"?

**Comment by Alex180689** [comment]
(Sorry, my PC is in Italian, but it should be understandable)
In Search bar search "environment variables". You should find something like this:

![Immagine 2024-01-06 160029](https://github.com/praydog/UEVR/assets/91917666/e6056c11-cd1d-4c2a-9c07-897a0c7fe7b4)
Here click on the highlighted button.

![Immagine 2024-01-06 155543](https://github.com/praydog/UEVR/assets/91917666/5c70087f-9f1c-4417-9261-377f23ab346c)
Now make sure you have these two variables containing the correct path to your dotnet installation.
If you didn't change anything during the .net installation, it should be the same path for you too.

**Comment by AceRimmer76** [comment]
Thanks, I really appreciate your help.  DOTNET was not in there at all for
me so I added it in and pointed it to where it is
located.  Unfortunately, that did not work.

Thanks for explaining that to me though.

**Comment by blastedsystem-wq** [comment]
Did anyone find a solutions for this ? I also installed and get the same error
