### ISSUE TITLE
Ace Combat 7 Player Control Mode

### ISSUE THREAD

**Issue by Okuma-JP** [praydog/UEVR#260]
I'm using UEVR nightly and a VR mod called UEVR Compatibility Mod (WIP), but the control method for the aircraft piloted by the player is set to "EXPERT mode", which makes it difficult to pilot. Could you please redesign and update it so that it can be piloted in "STANDARD mode" as well?

![Encode_1080P_1859 mp4_20190118_002249 546](https://github.com/praydog/UEVR/assets/149872126/9c7d3fb6-4762-4a2a-a0cf-e6a36332d990)

uevr nightlyを使用しながら、UEVR Compatibility Mod (WIP)という VR modを使用しているのですが、
プレイヤーが操縦する機体のコントロール方法が‘‘ EXPERTモード‘‘になっていて操縦が難しくて困っています。どうか‘‘STANDARDモード‘‘でも操縦出来るよう再設計、アップデートしていただけませんでしょうか?

**Comment by praydog** [comment]
This is not my or UEVR's obligation to resolve. You need to contact the mod developer for the compatibility mod.
