### ISSUE TITLE
[BUG] insurgency sandstorm is not detected when using xbox version of the game.

### ISSUE THREAD

**Issue by osoadsd** [praydog/UEVR#264]
I followed the instructions for insurgency sandstorm, and whenever i load the game it just doesnt appear on the menu to inject.

ive never used uevr before but i dont know what i did wrong.

Identify the UEVR version

beta 1.04

To Reproduce

Go to the files where the game with the disabled eac is
Make sure you launch the xbox version of the game
open uevr
See error

Expected behavior

uevr to detect and inject into insurgency.

Screenshots

![image](https://github.com/user-attachments/assets/ab3134d8-2c22-4548-8495-e8eb74e9093e)

PC Specs (please complete the following information):

Windows 10
Geforce rtx 3070
12th Gen Intel(R) Core(TM) i7-12700F
oculus quest 2
OpenXR
link cable
Dont know

**Comment by osoadsd** [comment]
![image](https://github.com/user-attachments/assets/9c431979-f517-4ab7-9a59-03c0b93f6921)

**Comment by praydog** [comment]
You haven't disabled EAC correctly. Use the Discord server or another platform for these kind of questions.
