### ISSUE TITLE
System button not bound to start/select

### ISSUE THREAD

**Issue by mkaflowski** [praydog/UEVR#266]
According to doc to use start and select I should use left system button. It doesnt work for me and when I use it I get SteamVr settings opened. I found that start button is bound to X+Y. Why? I cannot find that in UEVR and in SteamVR neither. Am I missing something?
Game tested: High on Life
Quest 3
Virtual Desktop

**Comment by praydog** [comment]
Use VDXR with Virtual Desktop, OpenXR in UEVR. Detecting the start button does not work with SteamVR as far as I know, because SteamVR overrides it for the overlay.

**Comment by mkaflowski** [comment]
Thank you. Using VDXR with Virtual Desktop fixed the problem :)
