### ISSUE TITLE
[BUG] "FMallocBinned2 Attempt to realloc an unrecognized block 000002413BC60000   canary == 0x0 != 0xe3" crash

### ISSUE THREAD

**Issue by ppaneksamsung** [praydog/UEVR#267]
**Describe the bug**

Hello, I would like to report a bug that a game process crashes during termination. It happens on DX11 games: ARD, Dragon Ball Z: Kakarot, Stray. I tested on https://github.com/praydog/UEVR-nightly/releases/tag/nightly-930-0958bb718cbc83d878deb246660bf14b20a83599 and https://github.com/praydog/UEVR/releases/tag/1.04. Is it a known issue or something that can be fixed easily?

**Upload logs and any crash dumps**

UEVR-specific logs and crash dumps:

[ARD-Win64-Shipping.zip](https://github.com/user-attachments/files/16328870/ARD-Win64-Shipping.zip)

Game-specific crash dumps:

[UE4CC-Windows-9C09F84D48FAF016A59ACB9E7DFAB148_0000.zip](https://github.com/user-attachments/files/16328885/UE4CC-Windows-9C09F84D48FAF016A59ACB9E7DFAB148_0000.zip)

**Identify the UEVR version**

0958bb718cbc83d878deb246660bf14b20a83599 or 1.04

**To Reproduce**

1. Launch "A.R.D. Alien Removal Division" game. Game ID is 1768550.
2. Inject UEVR.
3. Terminate the game.

**Expected behavior**

A game should be terminated without error.

**Screenshots**

![image](https://github.com/user-attachments/assets/658250e8-eb1f-4cfd-8d88-09c62baadd03)

**PC Specs (please complete the following information):**
 - Windows 11
 - RTX 4070 laptop
 - i7-13700HX
 - N/A (we use custom OpenVR driver)
 - OpenVR

**Comment by praydog** [comment]
It's known, and it can be fixed easily, but it's actually not that simple. Trying to fix this would need testing across hundreds, or thousands of games. So I don't rush to immediately try and fix it.

Basically `FMalloc` global needs to be resolved, along with `FMalloc::Malloc`. Then `new` calls for the SceneViewExtensions need to be replaced with `FMalloc::Malloc`. This is trivial to do, as UEVR already has code for this, but FMalloc isn't 100% guaranteed to be resolved correctly on every game. Just trying to keep the core functionality intact.

**Comment by praydog** [comment]
Fixed in faa3ff0000973590b20a91de07ccddd9693dc9af with a new option

However the new option is off by default as it's unknown whether this works on all games or not. So will have to be manually turned on.

**Comment by ppaneksamsung** [comment]
Thank you very much for quick fix :)
