### ISSUE TITLE
2D screen mode bindable shortcut

### ISSUE THREAD

**Issue by kenthinson** [praydog/UEVR#269]
**Is your feature request related to a problem? Please describe.**
I am playing Kingdom Hearts 3. I would like to be able to activate the 2D screen view when in the story cut-scenes to get the original intended experience as there are some goofy animations that are distracting happening outside the intended view. But I want to do the game-play part in full 3D VR. To that end it would be nice to have some kind of shortcut to toggle between the two easily without having to bring up the whole UEVR menu and cover up the story beat that is happening. Or having to remember to pause the game and switch. 

**Describe the solution you'd like**
A way to toggle between 2D screen view and VR view using some kind of bindable shortcut. 

**Describe alternatives you've considered**
It would be cool if this could happen automatically instead of having to use a keybind. But I have no idea where to start looking for a way to detect the transition between story / game-play automatically. So I think the keybind is more feasible

**Additional context**
Loving UEVR and playing kingdom hearts 3 in it. Thanks for your hard work Praydog!

**Comment by kenthinson** [comment]
Related to this would it be possible to control the resolution of the 2D view somehow? It's kind of blurry compared to the VR view.

**Comment by praydog** [comment]
There already is a keybind for this under "keybinds".

**Comment by kenthinson** [comment]
Oh I'm so sorry! I missed it. Thank you
