### ISSUE TITLE
[Feature request] DYNAMIC foveated rendering with PSVR2

### ISSUE THREAD

**Issue by randomVRguy** [praydog/UEVR#271]
I know this is a bit of speculation, but still: **Do you see a chance to somehow enable the PSVR2's eye tracking hardware for the purpose of DFR in UEVR?** This combination (UEVR with PSVR2 using DFR) would be a blast.

The reason I'm bringing this up here is the following. From a logical point of view, the eye tracking in PSVR2 _must_ be accessible on the PC. Why? First, Sony can neither use the adapter box nor the headset itself to disable it somehow, because you can take a random PSVR2 and connect it directly to a PC via a VirtualLink port (RTX2000 series / RX 6|7000 series). 
Secondly, you can switch with the headset between PS5 and PC at any time. And at PS5, the ET "suddenly" works. So the signal has to be present at the cable all the time and is therefore theoretically accessible. 
The only way Sony could disable it on purpose is via their SteamVR app, so just software-wise. Or, perhaps more likely, they didn't disable anything and just didn't provide the feature to save some effort.

**Comment by praydog** [comment]
Duplicate issue #44
