### ISSUE TITLE
[BUG] UEVR jedi fallen order full blurred

### ISSUE THREAD

**Issue by jadmanxxx** [praydog/UEVR#272]
The game worked great at first, then I had to go into a cave and then everything became extremely blurred. I can't play it anymore. Help
![IMG_7529](https://github.com/user-attachments/assets/53b798b1-15da-488e-8bb3-7db7e46ae07c)

**Comment by praydog** [comment]
This is a game-specific issue that can likely be fixed by turning off a motion blur setting. I don't deal with game-specific issues on the GitHub page, and these types of issues should be discussed on the [Flat2VR Discord](http://flat2vr.com).
