### ISSUE TITLE
[BUG] Getting "openxr instance -2" on Hogwarts Legacy

### ISSUE THREAD

**Issue by chaminar2** [praydog/UEVR#275]
I just started trying to use OpenVR, I decided to test it on Hogwarts Legacy. I have Virtual Desktop, and a Quest 2. I have set my  runtime in virtual deskeop to VDXR, and have my oculus quest link app OpenXR runtime set to steamVR, aswell as my SteamVR Settings OpenXR runtime set to SteamVR. Ive also tried setting the oculus runtime to default to oculus link, but that returned a -32 error code. 

this is an earlier screenshot not the -2 one, I will upload that one in comments
![imageewq](https://github.com/user-attachments/assets/5126e6d4-d2db-4ce7-8b32-fbc41e117d8b)

[HogwartsLegacy.zip](https://github.com/user-attachments/files/16685398/HogwartsLegacy.zip)

**Comment by praydog** [comment]
This is not a UEVR issue.
