### ISSUE TITLE
Maybe exclude Windows Mixed Reality portal from inject dropdown?

### ISSUE THREAD

**Issue by joschi127** [praydog/UEVR#28]
Minor and low priority, but maybe an easy and nice improvement.

In my inject dropdown I always see Windows Mixed Reality portal as first entry:

![image](https://github.com/praydog/UEVR/assets/1758468/809daeac-5972-4a91-b0c8-fe00f7ecd8b0)

Would be nice and even more easy to use if this would be hidden and so typically the first and only entry in the dropdown would be the game currently running.

**Comment by praydog** [comment]
Fixed in https://github.com/praydog/uevr-frontend/commit/a95a7971bd3c37f5c554023fbf13f6ca0f00a0e5

Will be in the next release
