### ISSUE TITLE
[BUG] UE5 Game "The Isle" is not recognized

### ISSUE THREAD

**Issue by s-koenig92** [praydog/UEVR#285]
Hi,

I'm trying to play The Isle with UEVR. It's Unreal Engine 5 and it's running as administrator (manually started with "Run as Administrator"), but UEVR doesn't list the process "TheIsleClient-Win64-Shipping" at all... :(
It's also a 64 Bit application, I know 32 Bit is not supported, but this should not be a issue here...

UEVR is also running as administrator.

Any ideas? :)

![the_isle_evrima_uevr_2024-09-25](https://github.com/user-attachments/assets/706614b1-7f39-4e12-8f34-205a025e5786)

**Comment by s-koenig92** [comment]
Satisfactory works well, by the way. So UEVR is generally working fine :)

**Comment by praydog** [comment]
Games with anti-cheat are not supported.
