### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by InHard2** [praydog/UEVR#286]
Hey i cant seem to make Any RE games with the vr mod work, in the screen it looks fine and the rotation doesnt lag or frezze, but in my vr headset it frezzes when i look too muhc to teh right ot left

PC Specs
 - Windows 11
 - rtx4060ti
 - Intel i5-12400f
 - None(using an app called Iriun VR)
 - OpenXR or OpenVR(Not sure but is normal RE Village)

**Comment by praydog** [comment]
Not related to UEVR
