### ISSUE TITLE
Controller Pitch rotation offset

### ISSUE THREAD

**Issue by Hawat3000** [praydog/UEVR#29]
Hello, I am trying to make a 90º pitch rotation for the VIve controller. 
The yaw and roll angles are ok but you have to overthrow the controller to aim
I have seen that there is a "rotation_offset" in the profile json file with w, x, y and z values but I dont understand how it works (are they quaternion?) I have test different values in every angle with not luck.
Also I have try to adjust with the gui but I cant see the model
Can someone guide me how these values works?
Regards

**Comment by praydog** [comment]
Added in 167a1afd0011fa4dd6afd56372664d11cc1eee5f

Developer builds can be downloaded in https://github.com/praydog/UEVR/actions
or you can wait until the next release
