### ISSUE TITLE
[BUG] Crash when entering the tunnel

### ISSUE THREAD

**Issue by andyalpa** [praydog/UEVR#300]
**Describe the bug**

The game crash for me every time I get into a door after following Laura through the street of Silent Hill at night. The place I get after I open that door seems to be some kind of tunnel but the crash happens like 5 seconds after I get in

**Upload logs and any crash dumps**

If this is a game crash or game bug:

[SHProto-Win64-Shipping.zip](https://github.com/user-attachments/files/17856393/SHProto-Win64-Shipping.zip)

UEVR-specific logs and crash dumps:

* Click "Open Global Dir" in the injector frontend
* Navigate to the offending game folder
* Zip up the folder
* Upload to the issue

Game-specific crash dumps:

[UECC-Windows-DFFF8A0A4EE1CBF198A4788CF7B04AAB_0000.zip](https://github.com/user-attachments/files/17856404/UECC-Windows-DFFF8A0A4EE1CBF198A4788CF7B04AAB_0000.zip)

**Identify the UEVR version**

If the UEVR version or commit hash is known, submit this information.

**To Reproduce**

**Expected behavior**

**Screenshots**

**PC Specs (please complete the following information):**
 - Windows 11
 - Nvidia RTX 4090
 -Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz   3.60 GHz 
 - Quest 3
 - OpenXR 
 - Virtual Desktop
 - VDXR

**Comment by VegeraX** [comment]
Yes. It seems to be happening everytime you meet the upsidedown monster (I don't know the name it's the one hanging upside down under your feet)
It happens later in lambyrinth too, it crashes every time those monsters appear.
If you play flat it's fine but in VR those monsters crash the game, don't know why.

**Comment by VegeraX** [comment]
Lord Praydog already fixed it. 
Download the 0.3 version
