### ISSUE TITLE
[BUG] uevr-profiles.com is extremely overzoomed by default

### ISSUE THREAD

**Issue by NewsGuyTor** [praydog/UEVR#304]
**Describe the bug**

The CSS of uevr-profiles.com is messed up, it requires zooming way out to see a proper amount of content.

A 67% zoom level looks the best, but then the text is too small. 

Here are images that show the flaws (I've cut off the sideberry tab sidebar as that contained private info)

100% zoom:
<img width="1174" alt="100" src="https://github.com/user-attachments/assets/3c394634-3c6c-43eb-8e39-78bd1409898b" />

80% zoom:
<img width="1174" alt="80" src="https://github.com/user-attachments/assets/8f65153f-faa2-446c-be33-c9225e04d205" />

67% zoom:
<img width="1174" alt="67" src="https://github.com/user-attachments/assets/13a09f82-8a7d-4338-a04b-14aef09ce156" />

**Comment by praydog** [comment]
Not my website.
