### ISSUE TITLE
Failed to inject plugin nullifier

### ISSUE THREAD

**Issue by ahoops33** [praydog/UEVR#31]
All I get is an error about a failed to inject plugin nullifier when i try to run quarry. Have uninstalled reinstalled 10 plus [times.open](https://times.open/) uevr, open game in steam, select game from drop down menu in uevr, make sure xr is selected and plugin slider on......I get NOTHING, just a flat screen version in my headset. I have NO IDEA how to resolve this failed to load plugin nullifier error and can find nothing online that works. When I go to the steam folder for game I see a plugin folder that is empty.

I do not want to lose more hours trying other games if I cannot even get this to open in 3d due to error message. very frustrating and does not feel user friendly to me. running windows 11 added uevr so defender would not block it but nothing helps. I have lost sooooo many hours to trying this that I almost do not care about this app anymore.

**Comment by praydog** [comment]
Install the latest build (1.01) that has fixed this issue: https://github.com/praydog/UEVR/releases/latest/download/UEVR.zip

If not:
1. Ensure no other anti-viruses are running
2. Move UEVR to a different folder, the folder you have it in may be too restrictive for the game to try and load UEVR

**Comment by ahoops33** [comment]
Thank you before I do this are you suggesting I move the UVR injector.EX E file to a different folder?
   
   
   
    On 01/02/2024 1:31 PM PST praydog ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Install the latest build (1.01) that has fixed this issue: https://github.com/praydog/UEVR/releases/latest/download/UEVR.zip 
   If not: 
    
    Ensure no other anti-viruses are running 
    Move UEVR to a different folder, the folder you have it in may be too restrictive for the game to try and load UEVR

**Comment by praydog** [comment]
I am saying move ALL of UEVRs files to a different folder.

**Comment by ahoops33** [comment]
Thank you I got it to work. It just doesn’t look very good so it might not be one of those games that works well.
   
   
   
    On 01/02/2024 4:21 PM PST praydog ***@***.***> wrote:
    
   
     
    
   
     
    
     
   I am saying move ALL of UEVRs files to a different folder.
