### ISSUE TITLE
[BUG] Robocop BuildId 12745053 (installed 1/3/24) crashing

### ISSUE THREAD

**Issue by jcuzens** [praydog/UEVR#38]
**Describe the bug**

Game crashes frequently, generally doesn't make it past the intro video when creating a new campaign. Tried turning all settings to LOW, used the RoboCop profile from the UEVR supported games link. Tried changing from NATIVE to SEQUENTIAL. 

Quest 3 -- attempted using VDXR and SteamVR separately to see if that was the issue. Used OpenXR in both cases. 

**Upload logs and any crash dumps**

If this is a game crash or game bug:

UEVR-specific logs and crash dumps:

[RoboCop-Win64-Shipping-Crashed.zip](https://github.com/praydog/UEVR/files/13817130/RoboCop-Win64-Shipping-Crashed.zip)

Game-specific crash dumps:

[UECC-Windows-F4B58602417DD3D4F17CBF973D1ECF38_0000.zip](https://github.com/praydog/UEVR/files/13817136/UECC-Windows-F4B58602417DD3D4F17CBF973D1ECF38_0000.zip)

**Identify the UEVR version**

5.2.0-194826

**To Reproduce**

1) Start UEVR
2) Put on Quest 3
3) Start Virtual Desktop (VDXR runtime)
4) Connect to PC
5) Start Robocop via Steam (not Steam VR)
6) Tab out to UEVR and inject once at the menu
7) Set height
8) Start new campaign
99% of the time the game will crash

**Expected behavior**

Expect the game to not crash.

**Screenshots**

**PC Specs (please complete the following information):**
 - Windows 11
 - Asus TUF 4070ti
 - Ryzen 5 5600x
 - Quest3
 - OpenXR
 - Virtual Desktop
 - VDXR
[log.txt](https://github.com/praydog/UEVR/files/13817122/log.txt)

**Comment by praydog** [comment]
Disable OpenXR Toolkit, looks like it's crashing in that DLL. Not sure at the moment whether I need to fix this or if this is a bug in OXRTK or I need to fix this, so just closing this for now as this is third party software.

**Comment by Asryan2a** [comment]
I have the same issue impossible to play the game. How do i disable this?

thanks

**Comment by jcuzens** [comment]
I can confirm that disabling the OpenXR toolkit did SIGNIFICANTLY reduce crashes. I will note that I only played once after doing this (just haven't had the time) and made it way further. I still encountered a crash but it was 30 minutes into gameplay. Please see the following screenshot to see how to disable.

![uever](https://github.com/praydog/UEVR/assets/5082683/fd5b949e-3732-4009-8132-82db865087d1)

**Comment by Asryan2a** [comment]
I still have issue with it, what am i doing wrong? the game is launching but unplayable all is flickery
