### ISSUE TITLE
[ERROR] Could not create openxr system: XR_ERROR_FORM_FACTOR_UNAVAILABLE

### ISSUE THREAD

**Issue by andykiting** [praydog/UEVR#39]
**Describe the bug**

I want to use the meta quest 3 VR to play HogwartsLegacy in Steam on windows 11 desktop. When I launch UEVR and press inject using OpenXR setting, everytime the VR Runtime displays following error: 

OpenXR not loaded: Could not create openxr system: XR_ERROR_FORM_FACTOR_UNAVAILABLE
OpenVR not loaded: openvr_api.dll not found
Please select OpenVR from the loaded if you want to use OpenVR

The game doesn't switch to VR mode, it continues to run in non-VR mode.

Find attached the UnrealVRMod log file
[HogwartsLegacy.zip](https://github.com/praydog/UEVR/files/13817897/HogwartsLegacy.zip)

<img width="540" alt="XR_ERROR" src="https://github.com/praydog/UEVR/assets/155521596/b534e1f2-0360-4122-bf82-36299c3088a2">

**PC Specs (please complete the following information):**
 - OS: windows 11
 - Graphics card: NVIDIA GeForce RTX3090
 - CPU: AMD 5950X
 - Headset Model: meta quest 3
 - Streamer Virtual Desktop version with setting OpenXR Runtime = VDXR
 - Connect in headset using Virtual Desktop and also Steam link

Whatever setting I try I always get the same error message and the game doesn't switch to VR mode. I installed UEVR also in different folder locations without any access restrictions, also no success.

Any help for what I could try different/more is welcome.

Thanks

**Comment by h4rpun3** [comment]
Exactly the same thing happens to me, no matter which game I try to start.
Would be really nice to get some advice here :)

**Comment by itsDustin** [comment]
I was facing the same error message for my setup. I managed to get it running, so maybe a similar approach can be helpful for different setups as well.

OS: windows 10
Graphics card: NVIDIA GeForce RTX 3080ti
CPU: Intel i7 11700k
Headset Model: meta quest 3
Streamer: Quest Link (cable)
PC: Oculus App

Solution:
After I set Oculus as the active openXR Runtime the issue disappeared.
(Oculus App in Windows > Settings > General > "Open XR Runtime" click on "set Oculus as active"

**Comment by andykiting** [comment]
I managed to get the game running in VR mode in the following setup by checking / resetting the settings in the following applications:

**on PC:**
1.Start Steam app and within Steam launch SteamVR. Check Settings-->OpenXR. The current OpenXR Runtime was for whatever reason empty in my case. I changed / selected that in SteamVR
<img width="948" alt="PC_SteamVR" src="https://github.com/praydog/UEVR/assets/155521596/1020386a-5aaf-4451-b20c-ca48e15cccc9">

2.Start Oculus app. Check in Setting-->General the OpenXR Runtime. The text after 'Current OpenXR Runtime: ' was blank, for whatever reason no VR runtime was filled in. I changed/selected SteamVR. I clicked on Set Oculus as active but that didn't work. When going back to SteamVR app and in settings OpenXR I selected SteamVR again and that value was 'suddenly' displayed in Oculus app. However I don't start/use the Oculus app when running the game. I use Steam app and virtual desktop streamer app only.
<img width="1142" alt="PC_Oculus" src="https://github.com/praydog/UEVR/assets/155521596/17f3f813-859a-48da-a2ac-6ce4b344cf2a">

3. Start Virtual Desktop Streamer app. Go to Options. I selected the following values 
<img width="520" alt="PC_VirtualDesktopStreamer" src="https://github.com/praydog/UEVR/assets/155521596/1036fb5b-a9bc-4c77-bcfd-9b350f014042">

4. I closed all above apps and started on my PC only Steam app (and not launching Steam VR), Virtual Desktop Streamer and the UEVR app. After this I continued in Quest 3 device

**on Quest3**
1. Start Virtual Desktop and connect to PC wireless
2. using Quest 3 (seeing my desktop/PC) I launched HogwartsLegacy in Steam
3. using Quest 3 (seeing my desktop/PC) I injected the openXR settings using Synced Sequential as VR_RenderingMethod in the UEVR app
![PC_UEVR](https://github.com/praydog/UEVR/assets/155521596/be2f26bf-8225-4b9d-aa59-820f84065e4e)


and voila the game runs in VR. 

<img width="725" alt="PC_UEVR_result" src="https://github.com/praydog/UEVR/assets/155521596/37e54a58-df78-4eaf-8477-2defc6a8a92b">
