### ISSUE TITLE
Key Bind to Attach/Detach and Visible/Invisible for 3rd Person games

### ISSUE THREAD

**Issue by armax9** [praydog/UEVR#40]
**Is your feature request related to a problem? Please describe.**
When playing a third-person game and modifying settings to play in first-person mode (e.g., attaching to Acknowledged Pawn, making Character Mesh Invisible), there's an issue where the character becomes invisible in game dialogues, cutscenes, and cinematics. This also affects camera functionality in these scenes since it's tied to the character. Sometimes, developers even move the character off the map boundaries.

**Describe the solution you'd like**
I propose a solution where a key-binding feature allows players to toggle on/off the visibility of the character and the attach/detach of the camera to the character pawn. Probably possibility to use the same key for these setups. This would enable players to watch cutscenes and other in-game cinematic content without the character disappearing or camera issues.

**Comment by praydog** [comment]
Added in 
78125a50ea35354da3c77d9116de8e3f2ae7c257
9c2f7e76516a892fae1da82fa9796dee75defc11
