### ISSUE TITLE
Hogwarts Legacy closes immediately

### ISSUE THREAD

**Issue by LEGEND0S** [praydog/UEVR#43]
Hogwarts Legacy closes immediately after injecting.

Best regards
LEGENDOS

[HogwartsLegacy.zip](https://github.com/praydog/UEVR/files/13820912/HogwartsLegacy.zip)

**Comment by praydog** [comment]
Are you using any of the following?

Proton (for Linux)
ReShade

**Comment by LEGEND0S** [comment]
Here a video of the issue:


https://github.com/praydog/UEVR/assets/76971460/6b8a25c4-700b-4c24-9301-1524e7af0166


Best regards
legendos

**Comment by nucleiis** [comment]
I have no issue with Injecting. I am using OpenVR though

**Comment by LEGEND0S** [comment]
@nucleiis

First, thanks for your reply.

I have tried all possible options.

I reinstalled Windows last night.
After that I only installed the necessary drivers.

Then I started Hogwarts and clicked on inject... unfortunately Hogwarts closes again immediately.

Now I'm at the end of my options. )-:

Best regards!

**Comment by praydog** [comment]
Are you running a pirated copy of the game?

**Comment by LEGEND0S** [comment]
I bought the game last year.

Since the copy protection only causes problems (even when starting), I use the crack from Empress, yes.

If it helps you, i can upload the proof of purchase for you so you can see that I own the original game.

Best regards!

**Comment by witan777** [comment]
Reproduced with env:
- HP Reverb G2 (Windows Mixed Reality)
- RTX 3080 (GeForceGame Ready Driver 12/12/2023)
- Windows 10 22H2
- Hogwarts Legacy Build 1117238 + **Empress crack**

**Comment by praydog** [comment]
Pirated copies are out of scope.
