### ISSUE TITLE
UObjecthook  Crashes Hogwarts Legacy [BUG]

### ISSUE THREAD

**Issue by armax9** [praydog/UEVR#46]
When you enable the advanced settings and you go to the uComponents tab thing to load in all the props and components, there are only 400,000, but the game always freezes within 5 minutes or so.
Also, I can't do anything in uObjectHook menu for more than 2 minutes, should act fast or the game will crash.

Probably, make sense to add the button to pause real-time monitoring of uComponents?

**Comment by praydog** [comment]
Upload crash dumps (`.dmp` files) from `%LOCALAPPDATA%\{the-game-name}\Saved\Crashes` if you can.

**Comment by armax9** [comment]
Thank you! Sure. Attaching, not sure which one is related to this problem, but I think all of them (sometimes I had to kill the process with the task manager, because the whole system hung)
The link for dumps - https://drive.google.com/file/d/1zRmrnXTOuK-nJnLfjEPbVF-4HICe_EK0/view?usp=sharing

**Comment by praydog** [comment]
Fixed the memory leak. Will be in next release.

**Comment by ahmedaldafaae** [comment]
I am using version 1.03 which is the new one as of now but the game keeps crashing

**Comment by ahmedaldafaae** [comment]
Also the guide diagram for adjust the Astronomy Table Locations is not shown up in the VR but shown on the flat screen

**Comment by praydog** [comment]
Just saying it crashes is not enough for me. You need to make a new issue and follow the instructions in the template.

**Comment by ahmedaldafaae** [comment]
Thank you. I will do so
