### ISSUE TITLE
UEVR not identifying the PID

### ISSUE THREAD

**Issue by Watsonid** [praydog/UEVR#47]
When I open UEVR and the "Works Perfectly" tested game (Life is Strange) on steam, it will not identify the PID for any steam game I try. The game is running, and open, and the dropdown is blank. It will identify other random things like Task manager PID, but no steam games. 

I have talked with a few people on the Flat2VR discord server and several people are having the same issue of nothing appearing in the dropdown even though the game is open and running.

![blank PID dropdown](https://github.com/praydog/UEVR/assets/85996145/3bef8bff-18d9-4783-ad03-5a7b4367c8bf)

Sadly I cannot upload anything from the Global Dir because it adds nothing since it wont identify. I am using newest version of UEVR 1.1. 

I have tried Rai Pal with the same issues of it not identifying any steam game PIDs.

Here are my steps:

1. Launch UEVR, default settings with OpenXR and Nullify VR Plugins selected
2. Launch the game ( Life is Strange )
3. Process does not appear in the dropdown or identify the game or any games
4. UEVR does identify some processes I may have open like Task Manager

I've checked and the game is running and has a PID number, but UEVR wont identify it. Is there possibly a way to manually input a PID number?

PC Specs:
 - Windows 11 Pro
 - RTX 3070
 - CPU: i7 11th Gen
 - Quest 3
 - OpenXR
 - Attempted with Steam link, and oculus link cable
 - Attempted with Oculus desktop app, and Steam VR

**Comment by praydog** [comment]
Life is Strange or Life is Strange: Remastered?

**Comment by isaiahfuller** [comment]
I'm having this issue as well. Seems like it's only detecting programs running as administrator.

**Comment by praydog** [comment]
Closing as this seems to be the original Life is Strange. UE3. Out of scope. Can be-opened if this is not the case.
