### ISSUE TITLE
Show version somewhere in software

### ISSUE THREAD

**Issue by robbiered** [praydog/UEVR#48]
**Is your feature request related to a problem? Please describe.**
Show software version somewhere

**Describe the solution you'd like**
either have it in the header or "about"

**Comment by praydog** [comment]
Fixed in 60d3c7caf6bf7c0553a962c6f05304cc4e910f03, shows commit hash and build date in window title.

At least shows in the injected version, the frontend does not display the version yet.

Nightly/latest builds can be obtained from [here](https://github.com/praydog/uevr-nightly/releases/latest).
