### ISSUE TITLE
Support for Naissanceé

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [praydog/UEVR#49]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to use Naissanceé(free on steam at https://store.steampowered.com/app/265690/NaissanceE, try it, it's awesome) with uevr, but as it is Unreal 1.0.10917, it doesn't seem to load.

**Describe the solution you'd like**
I want to play Naissanceé in VR.

**Comment by praydog** [comment]
UE3 games are not supported. 32-bit games are not supported.

UE3 and 32-bit support is far out of scope for UEVR at the moment. Who knows what the future holds.
