### ISSUE TITLE
Game executable is not found in GUI

### ISSUE THREAD

**Issue by JakeAtRetroplay** [praydog/UEVR#51]
Whenever I try to open any UE4/UE5 game (Fortnite and PUBG are the ones I've tested), the game is not detected. 
Certain apps like my browser and other non Unreal Engine applications are detected. I'm running UEVRInjector as an admin aswell and have whitelisted it in Windows Defender.

![image](https://github.com/praydog/UEVR/assets/106899634/1ee57dff-8403-4d24-8cf6-ec8b6a3150ab)
(This is while PUBG is open.)

**To reproduce:**
Open UEVRInjector.exe
Open an Unreal 4/5 game like Fortnite/PUBG
Disable 'Nullify VR Plugins'
Attempt to locate game executable
It is not found

**Expected behavior**

The game executable is found

**There are no logs for me to upload from either PUBG or Fortnite, as the app has never detected either one.
**I am using UEVR version 'UEVR Beta 1.01'

**PC Specs:**
 - Windows 10 Home
 - NVIDIA RTX 3070 Ti
 - Intel i7-11700k
 - Meta Quest 2
 - OpenXR
 - Link Cable
 - Oculus (Home)

**Comment by praydog** [comment]
Not an issue. Games with anti-cheat are not supported and will not show up.
