### ISSUE TITLE
Pinball FX crashes upon injection 

### ISSUE THREAD

**Issue by BROHONKY** [praydog/UEVR#53]
Anytime I inject into Pinball FX the game instantly crashes and I can't seem to find any other reports of this happening.

Here is my crash log

[CrashContext.txt](https://github.com/praydog/UEVR/files/13826718/CrashContext.txt)

**Comment by praydog** [comment]
Looks like you have UObjectHook enabled. Do you need this?  I'll see if I can fix it though

**Comment by BROHONKY** [comment]
It's happening even with UObjectHook disabled

[CrashContext.txt](https://github.com/praydog/UEVR/files/13851567/CrashContext.txt)

**Comment by praydog** [comment]
This may be fixed in 53d6a13366b68743202df41514cc4e7cb4965e16 now

Developer builds can be obtained from the [Actions page](https://github.com/praydog/UEVR/actions)
