### ISSUE TITLE
UEVR made me like game graphics less

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [praydog/UEVR#58]
I used UEVR a few times and now I stopped. But not because the mod was bad, it's awesome. No, I started to realize, seeing it all in 3D, "being there" how everything is basic geometric shapes+ texture. Console? Cube + texture. Head? Sphere + texture. Platform? Plane + texture.

Once you're in there, are surrounded by the world the makers created, it just feels dull so quickly. I felt deceived.

I am aware developers do this for performance reasons, but they should rather focus on writing better engines for much more detail, like the "unlimited detail" hype that was once a fad.

I am writing that here, because it's here that people who have the same experience potentially gather.

What's your take?

**Comment by praydog** [comment]
Not an issue. Better to take these type of discussions to the [Flat2VR Discord](http://flat2vr.com)
