### ISSUE TITLE
[FEATURE REQUEST] A 3D virtual monitor mode

### ISSUE THREAD

**Issue by RafunkV** [praydog/UEVR#61]
The VR is really cool but there are games I have no chance at running at full VR resolutions.

I would love it if you could add an option to play in 3D on a virtual monitor. I wouldn't need to render as much and I wouldn't have to worry about all the tweaks needed for full VR.

I did see an option for 2D screen mode but having 3D would add so much for me.

**Comment by Pande4360** [comment]
Note that there are plenty of dx based 3d renderers out there, maybe try your luck with them first.

**Comment by RafunkV** [comment]
Would that work through a hmd?

**Comment by praydog** [comment]
2D screen mode IS 3D, fully stereoscopic. Only in OpenXR. In OpenVR it is 2D only right now.

**Comment by DrPepperBianco** [comment]
Hi @Pande4360,

can you give me an example of dx based 3d renderers? Especially for dx12? So far I found this. But this seems to be only working for VR, but not for regular 3D displays.
