### ISSUE TITLE
Cvars fail to load sometimes

### ISSUE THREAD

**Issue by Braxusx** [praydog/UEVR#63]
It seems to happen on most games except for a few like Kena Bridge of Spirits.
Under Cvars I keep seeing messages like "Failed to find Cvar"....   and it's often things like light culling or the upsampler setting.

I made a snapshot to show one of the games it keeps happening in. Which is Vampyr

Thanks!

![CVAR issue](https://github.com/praydog/UEVR/assets/85005371/ceee6eed-8fb4-41d5-8fca-75a34af6f219)

**Comment by praydog** [comment]
This may not necessarily be a bug. Not all of these CVars actually existing, depending on the engine version.
