### ISSUE TITLE
[BUG] ```Five Nights at Freddy's: Security Breach``` crashes when opening "Common Objects" tab in UObjectHook

### ISSUE THREAD

**Issue by Mangoletta** [praydog/UEVR#64]
- Game crashes after a few seconds after opening Common Objects tab in UObjectHook, however any other tab does not cause the issue.

Game Crash

UEVR-specific logs and crash dumps:
[Global Dir Folder](https://github.com/praydog/UEVR/files/13837260/fnaf9-Win64-Shipping.zip)

Game-specific crash dumps:

[UE4 Crash Dump](https://github.com/praydog/UEVR/files/13837250/UE4Minidump.dmp)

v1.01 (Latest Beta)

**To Reproduce**

1. Load Game and Inject UEVR
2. Open UObjectHook
3. Open Common Objects
4. Meshes and Blueprints in the back freak the hell out, flashing in and out of existence, before the game ultimately crashes

**Expected behavior**

It to not crash, don't really know how to explain more about this, Just for Common Objects to not crash the game

**PC Specs (please complete the following information):**

OS: Windows 11
GPU: RTX 3090
CPU: Ryzen 5 3600 6-Core
Headset: Quest 2 AND Quest 3
Runtime: OpenXR and OpenVR (tried both)
Streamer: Link, Virtual Desktop
Runtime: SteamVR, Oculus, and VDXR

**Comment by praydog** [comment]
Was able to reproduce, will try and fix

**Comment by praydog** [comment]
Fixed
