### ISSUE TITLE
RT shortcuts don't work with my controller (Playstation DS4 emulating Xbox 360 via DS4 windows) [BUG]

### ISSUE THREAD

**Issue by Ribonizer** [praydog/UEVR#75]
I've tried using the DS4 in native mode, in Xbox mode (Using DS4 windows, when it's like this as far as the PC is concerned this is a native Xbox controller), I've used my DS3 as well. Using R3+L3 will open the overlay menu but RT does nothing and doesn't bring up the camera controls shortcuts. Other RT shortcuts like recentering the view does not work. I have a Logitech F310 that works in native Xbox mode and in Direct Input mod, I have yet to test this one yet but I don't see why my DS4 would partially work the way it does right now, when in Xbox mode as far as the computer is concerned it's an Xbox controller.)

I wanna do further troubleshooting with this tonight, I'll update the bug report as I test a few more things but figured I'd get the ball rolling with the report.

Was using UEVR 1.01

**Expected behavior**

I would expect RT while the overlay to be open to produce a box in the UI and then allow me to fine tune the camera around with both controller sticks. The behavior works using my VR controllers but they are very unwieldly and this would be a game that I'd rather play with the controllers anyway. Plus it requires constantly adjusting the camera from scene to scene so I need a quick way to do this.

**PC Specs (please complete the following information):**
 - Windows 10
 - AMD 6700xt
 - Intel Skylake 6700k
 - Samsung Odyssey+ (WMR)
 - Tried both OpenXR and OpenVR
 - SteamVR

**Comment by praydog** [comment]
This depends on the game sometimes. If Steam Input has remapped RT to something else, it may not work. Is there a specific game? Have you tried it on different games?

**Comment by Ribonizer** [comment]
I've tried in both HotWheels and er... _another_ game. I'm fairly sure the other games does not have any bindings for RT. I'll try other stuff tonight to see if I can get it to work in any game. Are there any way to rebind this?

**Comment by Ribonizer** [comment]
Welp, looks like
