### ISSUE TITLE
UEVR Not recognising my game (squad)

### ISSUE THREAD

**Issue by germangarles** [praydog/UEVR#76]
Ive been trying to run Squad using my quest 2 with quest link using UEVR, but whenever I try inject it, it doesnt appear on my list of programs to inject. the only thing that appears in my programs list is my browser. I tried it with satisfactory and it worked perfectly however.

**Comment by praydog** [comment]
Not an issue. Games with anti-cheat are not supported and will not be supported. They will intentionally not show up. You'll need to disable EAC and play in singleplayer. You can discuss with other users what they're doing to play this game on the [Flat2VR Discord](http://flat2vr.com)
