### ISSUE TITLE
[BUG] Snap Turn with an Xbox Controller Not Working

### ISSUE THREAD

**Issue by Jarrod1937C** [praydog/UEVR#77]
When using an Xbox controller and enabling snap turn, the joystick just turns as normal. If this is application specific, What Remains of Edith Finch, is the last game I tried this with.

Latest version of UEVR as of this writing, 1.02

**To Reproduce**

1. While in game, go to input, enable snap turn.

**Expected behavior**

I would expect applying input to the joystick that rotates the camera to instead snap by the angle configured in the options.

**PC Specs (please complete the following information):**
 - Windows 10
 - Nvidia 4090
 - AMD 7800X3D
 - Varjo Aero
 - OpenVR

**Comment by emile0909** [comment]
+1
snap turn on gamepad right stick would greatly reduce motion sickness.
But I would consider it as a feature request instead of bug. And it's an important feature request.

**Comment by emile0909** [comment]
I think this is the commit to support snap turn on VR controllers.
https://github.com/praydog/UEVR/commit/725d1440b843ba0ba6d59881d69e81773c38d71a

@narknon is it possible to check gamepad right thumb stick, so that gamepad user can also snap turn? Thanks.

**Comment by saartk** [comment]
@emile0909 Thanks for identifying and closing my duplicate Issue. I would like to add +1 to this issue. Will help with motion sickness so much, which for me is worst in 3rd person games

**Comment by praydog** [comment]
Fixed in b79d00dab7c66dd6c22fb5e645db29636c3bf903

Developer builds can be downloaded from [the Actions page](https://github.com/praydog/UEVR/actions)
or you can wait until the next build is released

**Comment by Jarrod1937C** [comment]
Excellent! Thank you very much. That should make the injector accessible for a lot of people. Very much appreciated.

**Comment by emile0909** [comment]
Awesome! It helps a lot. Thanks.
