### ISSUE TITLE
Reset property to default-value

### ISSUE THREAD

**Issue by djchase** [praydog/UEVR#80]
Hi.

I've noticed that changing the resolution-scale slider back to 1 can be a little difficult, so I thought that:

It would be nice to be able to reset properties to their default-value, maybe by pressing a button on the right side of a property-widget.

It would be also nice if the default-value could be shown as well - if it is known.

If a property is changed multiple times, and made persistent, it could save the first value before it was changed, thus making the current value the default-value, as soon as it is changed the first time.

Thanks

**Comment by praydog** [comment]
Good idea. Should be really easy to add.

**Comment by praydog** [comment]
Added in b4885093dcb9eee73238208c66e5c84ad4743219
