### ISSUE TITLE
When i install it it says it detects a virus???[BUG]

### ISSUE THREAD

**Issue by hazzymad** [praydog/UEVR#83]
**Describe the bug**

A clear and concise description of what the bug is. If the bug only started to happen after a certain UEVR update, let us know which version the bug appeared in.

**Upload logs and any crash dumps**

If this is a game crash or game bug:

UEVR-specific logs and crash dumps:

* Click "Open Global Dir" in the injector frontend
* Navigate to the offending game folder
* Zip up the folder
* Upload to the issue

Game-specific crash dumps:

* These can usually be found in `%LOCALAPPDATA%/{the_game_name}/Saved/Crashes`
* Once found, zip up the folder and upload

**Identify the UEVR version**

If the UEVR version or commit hash is known, submit this information.

**To Reproduce**

**Expected behavior**

**Screenshots**

**PC Specs (please complete the following information):**
 - OS (e.g. Windows 11)
 - Graphics card
 - CPU
 - Headset Model
 - OpenXR or OpenVR
 - Streamer if applicable (Link, Air Link, Virtual Desktop, Steam Link, ALVR, etc...)
 - If using OpenXR, the runtime (Oculus, SteamVR, VDXR, PimaxXR, etc...)

**Comment by praydog** [comment]
Duplicate issue, and this may (or may not) be temporary. Simply the nature of how this program works. Injection like this is something commonly seen in malware, and it's easy for AVs to just blanket say it's a bad piece of software based on some behaviors it may be seeing.
