### ISSUE TITLE
Close button is hard to click

### ISSUE THREAD

**Issue by FolkSong** [praydog/UEVR#85]
This is just the desktop window, no VR needed. When you move the mouse cursor around within the close button (the "X" in the top right corner) it randomly switches between a pointing hand and a movement icon (see screenshot). If you click when the movement icon is shown the window doesn't close.

https://i.imgur.com/Hm33wO9.png

I think I figured out what's happening - it shows the hand when you're pointing at the lines of the "X" itself. But not the space in between the lines.

My suggestion is that when the cursor is anywhere within a box surrounding the "X", it should be a pointing hand and the window should close when clicked.

**Comment by praydog** [comment]
Fixed in [praydog/uevr-frontend/4221f08ec2c48ca14217b6a4baed45be65cb4d5b](https://github.com/praydog/uevr-frontend/commit/4221f08ec2c48ca14217b6a4baed45be65cb4d5b)

Will be in the next release
