### ISSUE TITLE
Failure to launch

### ISSUE THREAD

**Issue by spike4379** [praydog/UEVR#9]
windows 10, windows updated, ran as admin, exclusion added to windows security. exe runs, creates process then disappears, ran as admin also but no dice.

Anything I can try?

**Comment by o8615998** [comment]
If nothing happens when running UEVR, download .net 6.0.
This is a problem I just encountered. I recommend adding it to the readme.

**Comment by spike4379** [comment]
> If nothing happens when running UEVR, download .net 6.0. This is a problem I just encountered. I recommend adding it to the readme.

Absolute. champion. I could have sworn i had it installed for all my other python stuff but NOPE. Thank you :)

**Comment by spike4379** [comment]
Installed .net 6.0 SDK fixed it thanks to [o8615998](https://github.com/o8615998)

**Comment by lordbeavis** [comment]
i can confirm that installing the SDK and not just the runtime fixes this issue
