### ISSUE TITLE
[BUG]Scaling size of gun not saving in THE MULLER-POWELL PRINCIPLE.

### ISSUE THREAD

**Issue by BiggDaddyDann** [praydog/UEVR#92]
**Describe the bug**

A clear and concise description of what the bug is. If the bug only started to happen after a certain UEVR update, let us know which version the bug appeared in.

**Upload logs and any crash dumps**

If this is a game crash or game bug:

UEVR-specific logs and crash dumps:

* Click "Open Global Dir" in the injector frontend
* Navigate to the offending game folder
* Zip up the folder
* Upload to the issue

Game-specific crash dumps:

* These can usually be found in `%LOCALAPPDATA%/{the_game_name}/Saved/Crashes`
* Once found, zip up the folder and upload

**Identify the UEVR version**

If the UEVR version or commit hash is known, submit this information.

**To Reproduce**

**Expected behavior**

**Screenshots**

**PC Specs (please complete the following information):**
 - OS (e.g. Windows 11)
 - Graphics card
 - CPU
 - Headset Model
 - OpenXR or OpenVR
 - Streamer if applicable (Link, Air Link, Virtual Desktop, Steam Link, ALVR, etc...)
 - If using OpenXR, the runtime (Oculus, SteamVR, VDXR, PimaxXR, etc...)

**Comment by praydog** [comment]
Fixed a few days ago in d62737d677e5f556f577e13b01234205e32d8790

Dev builds can be downloaded from [Actions](https://github.com/praydog/UEVR/actions)
