### ISSUE TITLE
[BUG]Trying to compile with cmake in linux causes an error

### ISSUE THREAD

**Issue by mintylinux** [praydog/UEVR#95]
[cmkr] cmkr version 0.2.14
[cmkr] error: filesystem error: directory iterator cannot open directory: No such file or directory [/home/chuck/Desktop/UEVR-master/dependencies/submodules/spdlog/src]
CMake Error at cmkr.cmake:49 (message):
  
  cmkr_exec(/home/chuck/Desktop/UEVR-master/build/_cmkr_v0.2.14/bin/cmkr;gen;WORKING_DIRECTORY;/home/chuck/Desktop/UEVR-master)
  failed (exit code 1)
Call Stack (most recent call first):
  cmkr.cmake:220 (cmkr_exec)
  CMakeLists.txt:18 (cmkr)

**PC Specs (please complete the following information):**
 - Manjaro Linux
 - Nvidia RTX 3080
 - AMD Ryzen 9 5950X 16-Core Processor 
 - HTC Vive
 - OpenVR

**Comment by praydog** [comment]
Linux is not supported
https://github.com/praydog/UEVR/blob/master/COMPILING.md
