### ISSUE TITLE
[BUG] Clicking 'Adjust' after binding gun mesh closes interface and that's it

### ISSUE THREAD

**Issue by Warmotor** [praydog/UEVR#97]
**Describe the bug**

Finally found the weapon mesh in R:RC but my gun points 90deg to the right. Clicking 'Adjust' closes the UEVR interface but there is no element to map which way the gun points? Maybe I'm misunderstanding the function?

**Identify the UEVR version**

1.02 from Jan5

**To Reproduce**

1. Go to Weapon Mesh, it's under 'MySkeletalMesh', not the SkeletalMesh tied to your arms which is accessible from the top of the Pawn menu at the top of the tree. Took me forever to find, not sure exactly how to get back there but I can do it with some fiddling.
2. Attach Weapon Mesh to right hand, save and make permanent, gun now points to the right.
3. Click 'Adjust' on the connected mesh, interface closes and nothing happens.

**Expected behavior**

Online I've seen videos where a blue box pops up to map onto your gun?

**PC Specs (please complete the following information):**
 - Windows 10 Pro
 - RTX4080 16GB
 - Ryzen9 7900X
 - Quest 3 over link
 - OpenXR
 - Oculus Link (USB)
 - OpenXR runtime - Oculus

**Comment by praydog** [comment]
Not a bug. Open the menu again to finish adjustment

**Comment by praydog** [comment]
Sorry, I misunderstood at first and immediately closed it. Some games do not display the adjustment box for some reason unknown to me. If you can re-title the issue to something like "adjustment works but box doesn't show up" or something along these lines I can work with that
